#!/bin/sh
set -eu
R=/root/FREYA_IPHONE_ISH_NODE_888
O="$R/SHORTCUTS_BRIDGE_888/02_OUTBOX/ANDROID"
T="$(date -u +%Y%m%dT%H%M%SZ)"
C="IPHONE_TO_ANDROID_FIRST_CANARY_$T"
mkdir -p "$O/$C"
F="$O/$C/CANARY.env"
printf "PROTOCOL=888\nCANARY_ID=%s\nSOURCE_NODE=FREYA_IPHONE_ISH_NODE_888\nTARGET_NODE=FREYA_ANDROID_NODE_888\nSIGNAL_TYPE=FIRST_CANARY\nACK_REQUIRED=YES\nEXPECTED_ACK_CLASS=LOCAL_ANDROID_PROCESSING_RECEIPT\nAUTOMATIC_SEND=NO\nNETWORK_TRANSFER_EXECUTED=NO\nHUMAN_GATE=ACTIVE\nSTATUS=READY_FOR_ANDROID\n" "$C" > "$F"
H="$(sha256sum "$F"|awk '{print $1}')"
echo "CANARY_ID=$C"
echo "CANARY_PATH=$F"
echo "CANARY_SHA256=$H"
echo "NETWORK_TRANSFER_EXECUTED=NO"
echo "CANARY_SENT=NO"
echo "RESULT=READY_FOR_ANDROID_HANDOFF"
