#!/usr/bin/env python3
import os,json,hashlib,platform,datetime
from pathlib import Path
P=888;NODE="FREYA_IPHONE_ISH_NODE_888";B="IPHONE_888_BATCH_13_FINAL_LOCAL_PRODUCTION_SEAL_20260921";AUTH="DANIJELA_DJUROVIC_KESKIN"
OUT=Path("/root/IPHONE_888_FINAL_LOCAL_PRODUCTION_SEAL_20260921.env")
BASE=Path("/root/IPHONE_888_LOKALNI_h2a8tu_8")
PACK=Path("/root/mozak uzivo iphone/ZA_SLANJE/PAKET_cc5b080b7027_4c9fbcd725cb/IPHONE_ZA_ASUS_888.zip")
PINS={
"DOCUMENT_PROCESSOR":(BASE/"CODE/document_processor.py","8236c31e63747752248df5c70c13e7d3786dd53336387bb115a63fef5cc8f64d"),
"FINANCIAL_VALIDATOR":(BASE/"CODE/financial_validator_v2_888.py","97a77c63383646e81e56e2b5712714778dee6e4e9235b0d71e92cd1431a67db1"),
"TEST_RESULTS":(BASE/"TESTS/TEST_RESULTS.json","9df675914422d30abba2a0c4a6e21b0b5f7e0ca282ceb45ecca9d72bf1980de2"),
"REGRESSION_RESULTS":(BASE/"TESTS/REGRESSION_RESULTS.json","62e251abd5db2bc1de95233d8c00e0e52acf10c3a2ff569f5cfbdf05dffbad62"),
"CURRENT_REVIEW_PACKET":(PACK,"78afab0e896246906c9478fade3bff67185d45f37650c1139dbb751b8ad304fd")}
def emit(**x):print(json.dumps(x,ensure_ascii=False,sort_keys=True),flush=True)
def sha(q):
 h=hashlib.sha256()
 with q.open("rb") as f:
  for b in iter(lambda:f.read(1048576),b""):h.update(b)
 return h.hexdigest()
emit(PROTOCOL=P,NODE=NODE,BATCH=B,HUMAN_GATE="ACTIVE",HUMAN_GATE_AUTHORITY=AUTH,HUMAN_GATE_APPROVAL="BATCH_13_FINAL_LOCAL_PRODUCTION_SEAL",DEFAULT_MODE="DENY",FAIL_CLOSED="YES",CREATE_ONLY="YES")
a=Path("/etc/alpine-release")
if os.getuid()!=0 or not a.exists():
 emit(STATUS="HOLD",REASON="IPHONE_IDENTITY",NEXT="STOP");raise SystemExit(2)
if OUT.exists():
 emit(STATUS="HOLD",REASON="FINAL_SEAL_PATH_ALREADY_EXISTS_NO_OVERWRITE",path=str(OUT),NEXT="REVIEW_EXISTING_SEAL_ONLY");raise SystemExit(3)
for k,(q,e) in PINS.items():
 act=sha(q) if q.is_file() else None
 emit(event="PIN",component=k,path=str(q),expected=e,actual=act,match=(act==e))
 if act!=e:
  emit(STATUS="HOLD",REASON="CANONICAL_PIN_MISMATCH",component=k,NEXT="STOP");raise SystemExit(4)
# Prior-seal lineage: discover only, never modify.
prior=[]
for q in Path("/root").glob("*SEAL*.env"):
 try:
  if q!=OUT and q.is_file(): prior.append((str(q),sha(q)))
 except OSError: pass
ts=datetime.datetime.now(datetime.timezone.utc).isoformat()
lines=[
"PROTOCOL=888",f"NODE={NODE}","OPERATOR=DANIJELA_DJUROVIC_KESKIN",f"HUMAN_GATE_AUTHORITY={AUTH}",
"HUMAN_GATE=ACTIVE","DEFAULT_MODE=DENY","FAIL_CLOSED=YES","CREATE_ONLY=YES","PRODUCTION_SCOPE=LOCAL_HUMAN_GATED_DOCUMENT_AND_FINANCIAL_COMPONENTS_ONLY",
"DOCUMENT_PROCESSING=READY","FINANCIAL_VALIDATION=READY","KNOWLEDGE=PARTIAL","LOCAL_AUTOMATION=PARTIAL","ASUS_HANDOFF=PARTIAL","AGENTS=BLOCKED",
"DOCUMENT_PROCESSOR_SHA256="+PINS["DOCUMENT_PROCESSOR"][1],"FINANCIAL_VALIDATOR_SHA256="+PINS["FINANCIAL_VALIDATOR"][1],
"TEST_RESULTS_SHA256="+PINS["TEST_RESULTS"][1],"REGRESSION_RESULTS_SHA256="+PINS["REGRESSION_RESULTS"][1],
"CURRENT_REVIEW_PACKET_SHA256="+PINS["CURRENT_REVIEW_PACKET"][1],"EXACT_REFERENCES=43/43","NON_EXACT_OR_PARTIAL=0","TECHNICAL_UNRESOLVED=0",
"SEMANTIC_ACCURACY=NOT_ASSESSED","FINANCIAL_ACCURACY=NOT_ESTABLISHED","INFORMATION_FRESHNESS=NOT_ESTABLISHED","CURRENT_EXTERNAL_FACTS=NOT_ESTABLISHED",
"AGENT_PRODUCTION=HOLD","BACKGROUND_RUNTIME=NOT_STARTED","NETWORK_POLICY=LOCAL_ONLY_NO_NETWORK_ACTIONS","ASUS_SEND_AUTHORIZED=NO",
"AUTO_SIGN=DENY","AUTO_SEND=DENY","EXTERNAL_RELEASE=DENY","SOURCE_ORIGINALS_CHANGED=NO",
"PRIOR_SEAL_LINEAGE_JSON="+json.dumps([{"path":x,"sha256":h} for x,h in prior],separators=(",",":")),
"UTC_TIMESTAMP="+ts]
data=("\n".join(lines)+"\n").encode()
# Exclusive create, fail closed.
fd=os.open(str(OUT),os.O_WRONLY|os.O_CREAT|os.O_EXCL,0o600)
with os.fdopen(fd,"wb") as f:
 f.write(data);f.flush();os.fsync(f.fileno())
rb=OUT.read_bytes(); sealhash=hashlib.sha256(rb).hexdigest()
emit(event="SEAL_CREATED",path=str(OUT),bytes=len(rb),sha256=sealhash,SEAL_READBACK="PASS" if rb==data else "FAIL",prior_seals=len(prior))
if rb!=data:
 emit(STATUS="HOLD",REASON="SEAL_READBACK_FAIL",NEXT="STOP");raise SystemExit(5)
emit(PROTOCOL=P,NODE=NODE,BATCH=B,HUMAN_GATE="ACTIVE",HUMAN_GATE_AUTHORITY=AUTH,CREATE_ONLY="YES",WRITES=1,DELETIONS=0,OVERWRITES=0,NETWORK_ACTIONS=0,SOURCE_ORIGINALS_CHANGED="NO",STATUS="FINAL_LOCAL_PRODUCTION_SEAL_CREATED",FINAL_SEAL_PATH=str(OUT),FINAL_SEAL_SHA256=sealhash,SEAL_READBACK="PASS",ASUS_SEND_AUTHORIZED="NO",BACKGROUND_RUNTIME="NOT_STARTED",NEXT="RETURN_COMPLETE_OUTPUT_TO_MAGNUS")
