#!/bin/bash
LOG_FILE="$HOME/TITAN_HOLDING_2026/HOLDING_LOG.txt"

echo "=================================================="
echo "   TITAN HOLDING 2026 - KONTROLNI PRESEK SISTEMA   "
echo "=================================================="
echo "Datum provere: $(date)"
echo "--------------------------------------------------"

echo "🛡️ PROVERA DOKTRINA & INTEGRITETA:"
[ -f "$HOME/TITAN_HOLDING_2026/TITAN_DOKTRINA.md" ] && echo "  ✓ Doktrina sistema: AKTIVNA i učitana."
[ -f "$HOME/TITAN_HOLDING_2026/ARS_METAL/TITAN_SSOT_MASTER_ENHANCED.xlsx" ] && echo "  ✓ Integritet podataka: ARS Master SSOT osiguran."
[ -f "$HOME/TITAN_HOLDING_2026/ALGORITMI_I_TOKENI/MASTER_TOKEN_REGISTER_v4.0.json" ] && echo "  ⚙️ ALGORITAMSKI ENGINE: Tokeni i mrežni signali učitani."
[ -f "$HOME/TITAN_HOLDING_2026/DELTA_UNITY_HYDRA/DELTA_CORE_v1_0.py" ] && echo "  🐉 MREŽNA ARHITEKTURA: Hydra routeri i Delta Core verifikovani."
[ -f "$HOME/TITAN_HOLDING_2026/AI_SUVERENITET_888/BOG_ALGORITAM_DANIJELA_GROK_001.md" ] && echo "  ✨ AI SUVERENITET: Grok i Gemini moduli obezbeđeni."
[ -f "$HOME/TITAN_HOLDING_2026/BEBA_DELTA_ZASTITA/BEBA_DELTA_DASHBOARD.md" ] && echo "  👶 BEBA DELTA: Autonomni čuvar aktivan i budan."
[ -f "$HOME/TITAN_HOLDING_2026/PORODICNI_USTAV_MARIJA/PROTOKOL_888_Korak6_Palionica_DISK_MARIJA_Log.txt" ] && echo "  🌸 PORODIČNI USTAV CG: Marija Aktivna Memorija i Petra enkripcija osigurani."
[ -d "$HOME/TITAN_HOLDING_2026/MAREL_EKOSISTEM_FINANSIJSKI_MODEL" ] && echo "  📊 MAREL INŽENJERING: Finansijski ekosistem od 18.2M EUR i EIB paketi verifikovani."
[ -f "$HOME/TITAN_HOLDING_2026/SUPREME_DASHBOARD/TITAN_SUPREME_DASHBOARD_FINAL.xlsx" ] && echo "  👑 SVETI GRAL: Vrhovni Titan Dashboard osiguran."
echo "--------------------------------------------------"

echo "📊 ARS_METAL STANJE:"
ls -lh ~/TITAN_HOLDING_2026/ARS_METAL | grep -v "total"
echo ""
echo "🇹🇷 ADS_TURSKA STANJE:"
ls -lh ~/TITAN_HOLDING_2026/ADS_TURSKA | grep -v "total"
echo ""
echo "🌱 ECO_TRANSFORMER STANJE:"
ls -lh ~/TITAN_HOLDING_2026/ECO_TRANSFORMER | grep -v "total"
echo ""
echo "⚙️ ALGORITMI_I_TOKENI:"
ls -lh ~/TITAN_HOLDING_2026/ALGORITMI_I_TOKENI | grep -v "total"
echo ""
echo "🐉 DELTA_UNITY_HYDRA:"
ls -lh ~/TITAN_HOLDING_2026/DELTA_UNITY_HYDRA | grep -v "total"
echo ""
echo "✨ AI_SUVERENITET_888:"
ls -lh ~/TITAN_HOLDING_2026/AI_SUVERENITET_888 | grep -v "total"
echo ""
echo "🏛️ INSTITUCIONALNI_LENDER_PACK:"
ls -lh ~/TITAN_HOLDING_2026/INSTITucionalNI_LENDER_PACK | grep -v "total"
echo ""
echo "👶 BEBA_DELTA_ZASTITA:"
ls -lh ~/TITAN_HOLDING_2026/BEBA_DELTA_ZASTITA | grep -v "total"
echo ""
echo "🔑 KLJUCEVI_OD_DVORCA:"
ls -lh ~/TITAN_HOLDING_2026/KLJUCEVI_OD_DVORCA | grep -v "total"
echo ""
echo "🌸 PORODICNI_USTAV_MARIJA:"
ls -lh ~/TITAN_HOLDING_2026/PORODICNI_USTAV_MARIJA | grep -v "total"
echo ""
echo "📚 CHATGBT_LEKCIJE_I_STUBOVI:"
ls -lh ~/TITAN_HOLDING_2026/CHATGBT_LEKCIJE_I_STUBOVI | grep -v "total"
echo ""
echo "📊 MAREL_EKOSISTEM_FINANSIJSKI_MODEL:"
ls -lh ~/TITAN_HOLDING_2026/MAREL_EKOSISTEM_FINANSIJSKI_MODEL | grep -v "total"
echo ""
echo "👑 SUPREME DASHBOARD:"
ls -lh ~/TITAN_HOLDING_2026/SUPREME_DASHBOARD | grep -v "total"
echo "=================================================="
echo "Status: POTPUNI KORPORATIVNI I INDUSTRIJSKI KANON. Nadzor: CEO Danijela"

echo "[$(date)] Marel Engineering ekosistem uspešno sveden pod četrnaesti ustavni stub." >> "$LOG_FILE"
