#!/bin/bash
ROOT="/home/titangridmne/FREYA_BUILDER"
D1="$ROOT/99_DAEMON_RUN_GATE/DAEMON_001_RUN_GATE_ORCHESTRATOR"
DROP="/mnt/c/Users/titangrid.info/Desktop/FREYA_LENOVO_RECEIVER_DROPZONES/FROM_MAC"
PKT="FREYA_MAC_DISK_ANDROID_TO_LENOVO_PACKET_20260702_001724.tar.gz"
EXPECTED="3d74b850a770dac0ef8543f2b2ef3b8a9cf4bb0f0eb4133f4028812f170df5e9"

mkdir -p "$D1"

while true; do
  TS="$(date '+%Y%m%d_%H%M%S')"
  ACTUAL="MISSING"
  SHA_STATUS="NOT_AVAILABLE"
  PKT_STATUS="NO"

  if [ -f "$DROP/$PKT" ]; then
    PKT_STATUS="YES"
    ACTUAL="$(sha256sum "$DROP/$PKT" | awk '{print $1}')"
    [ "$ACTUAL" = "$EXPECTED" ] && SHA_STATUS="OK" || SHA_STATUS="FAIL"
  fi

  cat > "$D1/HEARTBEAT.md" <<HB
DAEMON_001_RUN_GATE_ORCHESTRATOR

LAST_HEARTBEAT=$TS
STATUS=ACTIVE

MAC_PACKET_RECEIVED=$PKT_STATUS
MAC_PACKET_SHA_STATUS=$SHA_STATUS

POLICY:
START_ALL_DAEMONS=NO
START_ONE_BY_ONE=YES
OLD_UNKNOWN_DAEMONS=BLOCKED
LEGACY_SCRIPT_RUNTIME=BLOCKED
AUTO_REPAIR=BLOCKED
DELETE=BLOCKED
MOVE=BLOCKED
UNPACK_WITHOUT_GATE=BLOCKED
HUMAN_GATE=ACTIVE

NEXT_ALLOWED:
DAEMON_002_RECEIVER_WATCHER_LIST_ONLY
HB

  echo "$TS DAEMON_001 heartbeat MAC_PACKET=$PKT_STATUS SHA=$SHA_STATUS" >> "$D1/daemon_001.log"
  sleep 30
done
