#!/usr/bin/env bash
set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 098R2R8"
echo " EVIDENCE CONTRACT REMEDIATION DECISION — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"

ROOT="/mnt/c/FREYA_ASUS_NODE_888"
AGENT_ROOT="$ROOT/03_AGENTS_ACTIVE/VALIDATED_PENDING_RUNTIME"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_098R2R8_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=098R2R8"
echo "MODE=READ_ONLY_EVIDENCE_CONTRACT_REMEDIATION_DECISION"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"

: > "$OUT/CONTRACT_STATUS.txt"
: > "$OUT/REMEDIATION_OPTIONS.txt"
: > "$OUT/MINIMUM_PRODUCER_CONTRACT.txt"
: > "$OUT/FINAL_STATUS.txt"

cat > "$OUT/CONTRACT_STATUS.txt" <<STATUS
AGENT_INPUT_CONSTRUCTION_STATUS=PROVEN
EVIDENCE_COMPLETE_CONSUMER_STATUS=PROVEN
EVIDENCE_COMPLETE_PRODUCER_STATUS=NOT_PROVEN

CONTRACT_IMPLEMENTATION_STATUS=INCOMPLETE

PILOT_FUNCTION=run_metadata_pilot
PILOT_EXECUTABLE_STATUS=BLOCKED_BY_MISSING_EVIDENCE_PRODUCER
STATUS

cat > "$OUT/MINIMUM_PRODUCER_CONTRACT.txt" <<'CONTRACT'
PROPOSED_COMPONENT=evidence_complete_producer

INPUT_TYPE=AgentDescriptor_OR_VERIFIED_AGENT_MAPPING

REQUIRED_INPUT_FIELD=agent_id
REQUIRED_INPUT_FIELD=relative_path
REQUIRED_INPUT_FIELD=sha256

REQUIRED_PRECONDITION=parse_status_PASS
REQUIRED_PRECONDITION=descriptor_validation_PASS
REQUIRED_PRECONDITION=registry_validation_PASS

OUTPUT_FIELD=agent_id
OUTPUT_FIELD=readiness_status

OUTPUT_REQUIRED_VALUE=readiness_status:EVIDENCE_COMPLETE

NETWORK_REQUIRED=NO
PACKAGE_INSTALL_REQUIRED=NO
SERVICE_REQUIRED=NO

SOURCE_FILE_MUTATION_REQUIRED=NO
ORIGINAL_AGENT_MUTATION_REQUIRED=NO
CONTRACT

cat > "$OUT/REMEDIATION_OPTIONS.txt" <<'OPTIONS'
OPTION_A=IMPLEMENT_MINIMAL_EVIDENCE_COMPLETE_PRODUCER
OPTION_A_SCOPE=LOCAL_CONTROL_PLANE_ONLY
OPTION_A_NETWORK=DENY
OPTION_A_EXTERNAL_SEND=DENY
OPTION_A_AGENT_TASK_EXECUTION=DENY
OPTION_A_ORIGINAL_MUTATION=DENY

OPTION_B=EXCLUDE_METADATA_PILOT_FROM_RUNTIME_QUALIFICATION
OPTION_B_EFFECT=METADATA_PILOT_REMAINS_UNQUALIFIED
OPTION_B_SYSTEM_EFFECT=OTHER_PROVEN_COMPONENTS_MAY_CONTINUE

RECOMMENDATION=OPTION_A
RECOMMENDATION_REASON=CONSUMER_CONTRACT_IS_PROVEN_AND_ONLY_PRODUCER_LAYER_IS_MISSING
OPTIONS

cat > "$OUT/FINAL_STATUS.txt" <<STATUS
PROTOCOL=888
NODE=FREYA_ASUS_DEBIAN_888

EVIDENCE_CONTRACT_REMEDIATION_DECISION=PREPARED

OPTION_A_STATUS=AVAILABLE
OPTION_B_STATUS=AVAILABLE

RECOMMENDED_OPTION=OPTION_A

IMPLEMENTATION_EXECUTED=NO
EVIDENCE_CREATED=NO
TARGET_FUNCTION_EXECUTED=NO
AGENT_EXECUTION_EXECUTED=NO

FILE_MUTATION_EXECUTED=NO
NETWORK_EXECUTED=NO
PACKAGE_INSTALL_EXECUTED=NO

AUTOMATIC_REMEDIATION=DISABLED

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
REPAIR_ALLOWED=NO

HUMAN_GATE_DECISION=REQUIRED
MODE=HUMAN_GATE_CONTROLLED
STATUS

echo "--- CONTRACT STATUS ---"
cat "$OUT/CONTRACT_STATUS.txt"

echo
echo "--- MINIMUM PRODUCER CONTRACT ---"
cat "$OUT/MINIMUM_PRODUCER_CONTRACT.txt"

echo
echo "--- REMEDIATION OPTIONS ---"
cat "$OUT/REMEDIATION_OPTIONS.txt"

echo
echo "--- FINAL STATUS ---"
cat "$OUT/FINAL_STATUS.txt"

echo "============================================================"
echo "RESULT=HOLD"
echo "BLOCKER=HUMAN_GATE_REMEDIATION_DECISION_REQUIRED"
echo "OPTION_A_NEXT=BATCH_098R2R9_MINIMAL_EVIDENCE_PRODUCER_IMPLEMENTATION_PLAN"
echo "OPTION_B_NEXT=BATCH_099_POST_CANARY_QUALIFICATION_WITH_METADATA_PILOT_EXCLUDED"
echo "REPORT_DIR=$OUT"
echo "============================================================"
