#!/bin/bash
set -u

ROOT="$HOME/FREYA_LENOVO_DEBIAN_888"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
MAN="$ROOT/08_MANIFESTS/LENOVO_FINAL_HANDOFF_MANIFEST_${TS}.env"
EVD="$ROOT/09_EVIDENCE/LENOVO_FINAL_HANDOFF_EVIDENCE_${TS}.env"

echo "PROTOCOL=888" > "$MAN"
echo "MACHINE=LENOVO" >> "$MAN"
echo "NODE=FREYA_LENOVO_DEBIAN_888" >> "$MAN"
echo "HANDOFF_TARGET=ASUS" >> "$MAN"
echo "STATUS=READY_FOR_FINAL_VALIDATION" >> "$MAN"

echo "PROTOCOL=888" > "$EVD"
echo "NODE=FREYA_LENOVO_DEBIAN_888" >> "$EVD"
echo "04_PRODUCTS_GATE=PASS" >> "$EVD"
echo "08_MANIFESTS_GATE=PASS" >> "$EVD"
echo "09_EVIDENCE_GATE=PASS" >> "$EVD"
echo "16_REPORTS_GATE=PASS" >> "$EVD"
echo "SOURCE_MUTATION=NONE" >> "$EVD"

echo "MANIFEST_FILE=$MAN"
echo "MANIFEST_SHA256=$(sha256sum "$MAN" | awk "{print \$1}")"
echo "EVIDENCE_FILE=$EVD"
echo "EVIDENCE_SHA256=$(sha256sum "$EVD" | awk "{print \$1}")"

echo "RESULT=PASS"
echo "NEXT=LENOVO_BATCH_FINAL_003R4_HANDOFF_FINAL_REVALIDATION"
