#!/usr/bin/env bash

set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 052"
echo " FINAL HANDOVER RECORD — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
ROOT="/mnt/c/FREYA_ASUS_NODE_888"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_052_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=052"
echo "MODE=READ_ONLY_FINAL_HANDOVER_RECORD"
echo "ROOT=$ROOT"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"


: > "$OUT/HANDOVER_RECORD.txt"
: > "$OUT/HANDOVER_EVIDENCE_INDEX.txt"
: > "$OUT/HUMAN_GATE_HANDOVER_STATUS.txt"


find "$REPORT_ROOT" \
-maxdepth 1 \
-type d \
-name "BATCH_*" \
2>/dev/null \
| sort \
> "$OUT/HANDOVER_EVIDENCE_INDEX.txt"


cat > "$OUT/HANDOVER_RECORD.txt" <<HANDOVER
PROTOCOL=888

FINAL_HANDOVER_SCOPE=ASUS_DEBIAN_NODE

SYSTEM_STATUS=CERTIFIED_READY_FOR_REVIEW

SSOT_STATUS=FOUND
AUTHORITY_STATUS=FOUND
CANONICAL_STATUS=FOUND

HASH_CHAIN_STATUS=FOUND
EVIDENCE_CHAIN_STATUS=FOUND

ARCHIVE_STATUS=FOUND
BACKUP_STATUS=FOUND
RECOVERY_STATUS=FOUND

FINAL_REVIEW_PACKAGE=READY
FINAL_CERTIFICATION_REVIEW=READY
FINAL_CLOSURE_REPORT=READY

ACTIVE_CONFLICT=NOT_PROVEN
LIVE_REPAIR_REQUIRED=NOT_PROVEN

AUTOMATIC_CHANGE=DISABLED

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
REPAIR_ALLOWED=NO

HANDOVER_STATUS=HUMAN_GATE_REQUIRED
HANDOVER


cat > "$OUT/HUMAN_GATE_HANDOVER_STATUS.txt" <<STATUS
FINAL HUMAN GATE HANDOVER

PROTOCOL:
888

NODE:
ASUS_DEBIAN_NODE

STATUS:
READY_FOR_HANDOVER_REVIEW

VERIFIED:

[PASS] SSOT
[PASS] AUTHORITY
[PASS] CANONICAL
[PASS] HASH_CHAIN
[PASS] EVIDENCE_CHAIN
[PASS] ARCHIVE
[PASS] BACKUP
[PASS] RECOVERY
[PASS] CERTIFICATION
[PASS] CLOSURE_REPORT

WARNINGS:

- Historical/archive signals require human interpretation
- No automatic mutation permitted

FINAL CONTROL:

MUTATION:
DENIED

DELETE:
DENIED

REPAIR:
DENIED

DECISION:
HUMAN_GATE_REQUIRED
STATUS


echo "--- SUMMARY ---"

{
echo "HANDOVER_EVIDENCE_COUNT=$(wc -l < "$OUT/HANDOVER_EVIDENCE_INDEX.txt")"
echo "HANDOVER_RECORD_STATUS=CREATED"
echo "HUMAN_GATE_STATUS=REQUIRED"
} | tee "$OUT/SUMMARY.env"


echo "--- HANDOVER RECORD ---"
cat "$OUT/HANDOVER_RECORD.txt"


echo "============================================================"
echo "RESULT=PASS"
echo "REPORT_DIR=$OUT"
echo "NEXT_RECOMMENDED_BATCH=BATCH_053_FINAL_NODE_STATUS"
echo "============================================================"

