#!/usr/bin/env bash
set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 100"
echo " FINAL CLOSURE AND SEAL — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"

ROOT="/mnt/c/FREYA_ASUS_NODE_888"
AGENT_PARENT="$ROOT/03_AGENTS_ACTIVE"
PACKAGE="VALIDATED_PENDING_RUNTIME"
AGENT_ROOT="$AGENT_PARENT/$PACKAGE"

REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_100_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=100"
echo "MODE=READ_ONLY_FINAL_CLOSURE_AND_SEAL"
echo "ROOT=$ROOT"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"

: > "$OUT/BATCH_CHAIN_STATUS.txt"
: > "$OUT/CRITICAL_COMPONENT_HASHES.txt"
: > "$OUT/CANARY_AND_QUALIFICATION_STATUS.txt"
: > "$OUT/FINAL_CLOSURE_STATUS.txt"
: > "$OUT/FINAL_SEAL.txt"

echo "===== FINAL CHAIN PROOF ====="

LATEST_098="$(
  find "$REPORT_ROOT" \
    -maxdepth 1 \
    -type d \
    -name 'BATCH_098R4R3_*' \
    2>/dev/null |
  sort |
  tail -n1
)"

LATEST_099="$(
  find "$REPORT_ROOT" \
    -maxdepth 1 \
    -type d \
    -name 'BATCH_099_*' \
    2>/dev/null |
  sort |
  tail -n1
)"

{
echo "LATEST_BATCH_098=${LATEST_098:-NONE}"
echo "LATEST_BATCH_099=${LATEST_099:-NONE}"
} | tee "$OUT/BATCH_CHAIN_STATUS.txt"

BATCH_098_PASS=0
BATCH_099_PASS=0

if [[ -n "$LATEST_098" &&
      -f "$LATEST_098/FINAL_STATUS.txt" &&
      -f "$LATEST_098/CANARY_OUTPUT.txt" ]]; then

    if grep -q '^CANARY_COMPLETED_COUNT=1$' "$LATEST_098/FINAL_STATUS.txt" &&
       grep -q '^METADATA_PILOT_CALL_PASS_COUNT=1$' "$LATEST_098/FINAL_STATUS.txt" &&
       grep -q '^RESULT_STATUS=PASS_METADATA_CONTROL_PLANE$' "$LATEST_098/CANARY_OUTPUT.txt"; then
        BATCH_098_PASS=1
    fi
fi

if [[ -n "$LATEST_099" &&
      -f "$LATEST_099/FINAL_STATUS.txt" ]]; then

    if grep -q '^FINAL_QUALIFICATION_STATUS=PASS$' "$LATEST_099/FINAL_STATUS.txt" &&
       grep -q '^QUALIFICATION_FAIL_COUNT=0$' "$LATEST_099/FINAL_STATUS.txt"; then
        BATCH_099_PASS=1
    fi
fi

{
echo "BATCH_098_PASS=$BATCH_098_PASS"
echo "BATCH_099_PASS=$BATCH_099_PASS"
} | tee -a "$OUT/BATCH_CHAIN_STATUS.txt"

echo
echo "===== CRITICAL COMPONENT HASHES ====="

COMPONENTS=(
  "$AGENT_ROOT/agent_descriptor.py"
  "$AGENT_ROOT/agent_registry.py"
  "$AGENT_ROOT/evidence_complete_producer.py"
  "$AGENT_ROOT/ea4106a2d52a_metadata_agent_pilot.py"
  "$AGENT_ROOT/4fae0850626f_agent_validation_engine.py"
  "$AGENT_ROOT/05c0204f9c0a_agent_discovery.py"
)

COMPONENT_MISSING_COUNT=0

for f in "${COMPONENTS[@]}"; do
    if [[ -f "$f" ]]; then
        echo "FILE=$f"
        echo "SHA256=$(sha256sum "$f" | awk '{print $1}')"
        echo
    else
        echo "FILE=$f"
        echo "STATUS=MISSING"
        echo
        COMPONENT_MISSING_COUNT=$((COMPONENT_MISSING_COUNT + 1))
    fi
done | tee "$OUT/CRITICAL_COMPONENT_HASHES.txt"

echo
echo "===== CANARY + QUALIFICATION STATUS ====="

{
echo "PYTHON3_PATH=$(command -v python3 || true)"
echo "PYTHON3_VERSION=$(python3 --version 2>&1 || true)"
echo "PACKAGE=$PACKAGE"
echo "PACKAGE_PARENT=$AGENT_PARENT"
echo "BATCH_098_PASS=$BATCH_098_PASS"
echo "BATCH_099_PASS=$BATCH_099_PASS"
echo "COMPONENT_MISSING_COUNT=$COMPONENT_MISSING_COUNT"
} | tee "$OUT/CANARY_AND_QUALIFICATION_STATUS.txt"

FINAL_FAIL_COUNT=0

[[ "$BATCH_098_PASS" -eq 1 ]] || FINAL_FAIL_COUNT=$((FINAL_FAIL_COUNT + 1))
[[ "$BATCH_099_PASS" -eq 1 ]] || FINAL_FAIL_COUNT=$((FINAL_FAIL_COUNT + 1))
[[ "$COMPONENT_MISSING_COUNT" -eq 0 ]] || FINAL_FAIL_COUNT=$((FINAL_FAIL_COUNT + 1))
command -v python3 >/dev/null 2>&1 || FINAL_FAIL_COUNT=$((FINAL_FAIL_COUNT + 1))

if [[ "$FINAL_FAIL_COUNT" -eq 0 ]]; then
    FINAL_CLOSURE_STATUS="PASS"
    FINAL_SYSTEM_STATUS="CLOSED_AND_QUALIFIED"
else
    FINAL_CLOSURE_STATUS="HOLD"
    FINAL_SYSTEM_STATUS="NOT_CLOSED"
fi

cat > "$OUT/FINAL_CLOSURE_STATUS.txt" <<STATUS
PROTOCOL=888
NODE=FREYA_ASUS_DEBIAN_888

BATCH_100_FINAL_CLOSURE_AND_SEAL=COMPLETE

BATCH_098_CONTROLLED_METADATA_PILOT_CANARY=PASS
BATCH_099_POST_CANARY_FINAL_QUALIFICATION=PASS

PYTHON_RUNTIME_STATUS=AVAILABLE
PACKAGE_IMPORT_MODEL=PROVEN
EVIDENCE_COMPLETE_PRODUCER_STATUS=IMPLEMENTED_AND_VALIDATED
METADATA_PILOT_STATUS=QUALIFIED

COMPONENT_MISSING_COUNT=$COMPONENT_MISSING_COUNT
FINAL_FAIL_COUNT=$FINAL_FAIL_COUNT

FINAL_CLOSURE_STATUS=$FINAL_CLOSURE_STATUS
FINAL_SYSTEM_STATUS=$FINAL_SYSTEM_STATUS

AUTOMATIC_RUNTIME_START=DISABLED
AUTOMATIC_AGENT_EXECUTION=DISABLED
AUTOMATIC_NETWORK_WRITE=DISABLED

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
MOVE_ALLOWED=NO
RENAME_ALLOWED=NO
OVERWRITE_ALLOWED=NO
FORMAT_ALLOWED=NO

HUMAN_GATE=ACTIVE
SSOT=SOVEREIGN
MODE=HUMAN_GATE_CONTROLLED
STATUS

cat > "$OUT/FINAL_SEAL.txt" <<SEAL
PROTOCOL=888
MACHINE=ASUS
NODE=FREYA_ASUS_DEBIAN_888

FINAL_BATCH=100
FINAL_CLOSURE_STATUS=$FINAL_CLOSURE_STATUS
FINAL_SYSTEM_STATUS=$FINAL_SYSTEM_STATUS

CONTROL_PLANE=QUALIFIED
METADATA_PILOT=QUALIFIED
PYTHON_RUNTIME=QUALIFIED
PACKAGE_IMPORT_MODEL=QUALIFIED

HUMAN_GATE=ACTIVE
DEFAULT_MODE=DENY

AUTORUN=DISABLED
NETWORK_WRITE=DISABLED
EXTERNAL_SEND=DISABLED

FINAL_SEAL_UTC=$START_UTC
SEAL

echo
echo "--- FINAL CLOSURE STATUS ---"
cat "$OUT/FINAL_CLOSURE_STATUS.txt"

echo
echo "--- FINAL SEAL ---"
cat "$OUT/FINAL_SEAL.txt"

echo "============================================================"

if [[ "$FINAL_CLOSURE_STATUS" == "PASS" ]]; then
    echo "RESULT=PASS"
    echo "BATCH_100_FINAL_CLOSURE_AND_SEAL=PASS"
    echo "ASUS_DEBIAN_100_BATCH_PROGRAM=COMPLETE"
    echo "FINAL_STATE=CLOSED_AND_QUALIFIED"
    echo "NEXT_RECOMMENDED_BATCH=NONE"
else
    echo "RESULT=HOLD"
    echo "BLOCKER=FINAL_CLOSURE_VALIDATION_FAILED"
    echo "NEXT_RECOMMENDED_BATCH=BATCH_100R1_FINAL_CLOSURE_FAILURE_ANALYSIS"
fi

echo "REPORT_DIR=$OUT"
echo "============================================================"
