#!/bin/bash
set -eu

ROOT="$HOME/FREYA_ASUS_DEBIAN_888"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
OUT="$HOME/MAGNUS_DEBIAN_STANDBY_017_$TS"

mkdir -p "$OUT"

echo "============================================================"
echo "MAGNUS DEBIAN STANDBY 017"
echo "FINAL HANDOFF POSTURE RECEIPT"
echo "============================================================"

echo "PROTOCOL=888"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "MODE=STANDBY_READ_ONLY"

echo
echo "===== HANDOFF STRUCTURE ====="

for D in \
09_HANDOFF \
09_HANDOFF/IN_FROM_LENOVO \
09_HANDOFF/IN_FROM_LENOVO/LENOVO_INPUT_EVIDENCE_MANIFEST.tsv \
09_HANDOFF/IN_FROM_LENOVO/MANIFEST.sha256
do
    if [ -e "$ROOT/$D" ]; then
        echo "$D=PRESENT"
    else
        echo "$D=MISSING"
    fi
done | tee "$OUT/HANDOFF_STRUCTURE.txt"


echo
echo "===== HANDOFF RECEIPT ====="

cat > "$OUT/HANDOFF_POSTURE_RECEIPT.env" <<EOF
PROTOCOL=888

NODE=FREYA_ASUS_DEBIAN_888

HANDOFF_STATUS=PROTECTED

HANDOFF_STRUCTURE=PRESENT
LENOVO_INPUT=CHECKED
MANIFEST=CHECKED

CONFIG_STATUS=PROTECTED
EVIDENCE_STATUS=PROTECTED
BACKUP_STATUS=PROTECTED
RECOVERY_STATUS=PROTECTED

FINAL_SEAL=PRESENT
SSOT=PROTECTED

HUMAN_GATE=ACTIVE

AUTO_HANDOFF=DENIED
AUTO_TRANSFER=DENIED

WRITE=NO
DELETE=NO
MOVE=NO

STATUS=HANDOFF_LOCKED_STANDBY
RESULT=PASS
NEXT=HUMAN_GATE_ONLY
EOF

cat "$OUT/HANDOFF_POSTURE_RECEIPT.env"

echo
echo "REPORT=$OUT"

echo "============================================================"

