#!/usr/bin/env bash
set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 089R2R2"
echo " APT METADATA REFRESH DECISION — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_089R2R2_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=089R2R2"
echo "MODE=READ_ONLY_APT_METADATA_REFRESH_DECISION"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"

: > "$OUT/APT_METADATA_EVIDENCE.txt"
: > "$OUT/HUMAN_GATE_DECISION.txt"

APT_GET_STATUS="MISSING"
command -v apt-get >/dev/null 2>&1 && APT_GET_STATUS="AVAILABLE"

APT_CACHE_STATUS="MISSING"
command -v apt-cache >/dev/null 2>&1 && APT_CACHE_STATUS="AVAILABLE"

APT_LIST_FILE_COUNT="$(
  find /var/lib/apt/lists \
    -maxdepth 1 \
    -type f \
    2>/dev/null |
  wc -l |
  tr -d ' '
)"

PYTHON3_CANDIDATE="$(
  apt-cache policy python3 2>/dev/null |
  awk '/Candidate:/ {print $2; exit}'
)"

PYTHON3_CANDIDATE="${PYTHON3_CANDIDATE:-NONE}"

{
echo "APT_GET_STATUS=$APT_GET_STATUS"
echo "APT_CACHE_STATUS=$APT_CACHE_STATUS"
echo "APT_LIST_FILE_COUNT=$APT_LIST_FILE_COUNT"
echo "PYTHON3_CANDIDATE=$PYTHON3_CANDIDATE"
} | tee "$OUT/APT_METADATA_EVIDENCE.txt"

if [[ "$APT_GET_STATUS" == "AVAILABLE" &&
      "$APT_CACHE_STATUS" == "AVAILABLE" &&
      "$PYTHON3_CANDIDATE" == "NONE" ]]; then

  REFRESH_REQUIRED="YES"
  PROPOSED_ACTION="HUMAN_GATE_APT_UPDATE_ONLY"

else

  REFRESH_REQUIRED="NO_OR_NOT_PROVEN"
  PROPOSED_ACTION="NO_METADATA_REFRESH_DECISION"
fi

cat > "$OUT/HUMAN_GATE_DECISION.txt" <<STATUS
PROTOCOL=888
NODE=FREYA_ASUS_DEBIAN_888

KNOWN_BLOCKER=APT_METADATA_NOT_READY

APT_METADATA_REFRESH_REQUIRED=$REFRESH_REQUIRED
PROPOSED_ACTION=$PROPOSED_ACTION

SCOPE_OF_POTENTIAL_CHANGE=APT_PACKAGE_INDEX_ONLY

PYTHON_INSTALL_INCLUDED=NO
PACKAGE_UPGRADE_INCLUDED=NO
DIST_UPGRADE_INCLUDED=NO
AGENT_EXECUTION_INCLUDED=NO

APT_UPDATE_EXECUTED=NO
INSTALL_EXECUTED=NO
UPGRADE_EXECUTED=NO

AUTOMATIC_NETWORK_WRITE=DISABLED
AUTOMATIC_INSTALL=DISABLED
AUTOMATIC_UPGRADE=DISABLED

NETWORK_WRITE_ALLOWED=NO
INSTALL_ALLOWED=NO
UPGRADE_ALLOWED=NO
MUTATION_ALLOWED=NO

HUMAN_GATE_DECISION=REQUIRED
STATUS

echo
echo "--- HUMAN GATE DECISION ---"
cat "$OUT/HUMAN_GATE_DECISION.txt"

echo "============================================================"
echo "RESULT=HOLD"

if [[ "$REFRESH_REQUIRED" == "YES" ]]; then
  echo "BLOCKER=HUMAN_GATE_APPROVAL_REQUIRED_FOR_APT_UPDATE"
  echo "NEXT_RECOMMENDED_BATCH=BATCH_089R2R3_APT_UPDATE_HUMAN_GATE"
else
  echo "BLOCKER=APT_METADATA_STATE_REQUIRES_FURTHER_ANALYSIS"
  echo "NEXT_RECOMMENDED_BATCH=BATCH_089R2R2R1_APT_METADATA_DEEP_ANALYSIS"
fi

echo "REPORT_DIR=$OUT"
echo "============================================================"
