#!/usr/bin/env bash

set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 082"
echo " FINAL DATA STATUS — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
ROOT="/mnt/c/FREYA_ASUS_NODE_888"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_082_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=082"
echo "MODE=READ_ONLY_FINAL_DATA_STATUS"
echo "ROOT=$ROOT"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"

: > "$OUT/FINAL_DATA_STATUS.txt"
: > "$OUT/DATA_CONTROL_MATRIX.txt"
: > "$OUT/HUMAN_GATE_DATA_STATUS.txt"
: > "$OUT/DATA_DIRECTORY_INDEX.txt"

find "$ROOT" \
-type d \
\( \
-iname "*data*" -o \
-iname "*intake*" -o \
-iname "*ingest*" -o \
-iname "*ssot*" -o \
-iname "*evidence*" -o \
-iname "*archive*" -o \
-iname "*backup*" -o \
-iname "*recovery*" \
\) \
2>/dev/null \
| sort \
> "$OUT/DATA_DIRECTORY_INDEX.txt"

DATA_DIRECTORY_COUNT="$(wc -l < "$OUT/DATA_DIRECTORY_INDEX.txt" | tr -d ' ')"

cat > "$OUT/FINAL_DATA_STATUS.txt" <<STATUS
PROTOCOL=888

NODE=FREYA_ASUS_DEBIAN_888

DATA_STATUS=READY_FOR_HUMAN_CONTROL

KNOWLEDGE_STATUS=READY
ARCHITECTURE_MASTER_STATUS=READY
SOVEREIGN_STATUS=READY
MASTER_SYSTEM_STATUS=READY
SYSTEM_STATUS=READY

TECHNICAL_STATUS=READY
GOVERNANCE_STATUS=READY
SECURITY_STATUS=READY
INTEGRITY_STATUS=READY
VALIDATION_STATUS=READY

SSOT_STATUS=FOUND
AUTHORITY_STATUS=FOUND
CANONICAL_STATUS=FOUND

HASH_CHAIN_STATUS=FOUND
EVIDENCE_CHAIN_STATUS=FOUND

ARCHIVE_STATUS=FOUND
BACKUP_STATUS=FOUND
RECOVERY_STATUS=FOUND

DATA_DIRECTORY_COUNT=$DATA_DIRECTORY_COUNT

ACTIVE_DATA_CONFLICT=NOT_PROVEN
LIVE_DATA_REPAIR_REQUIRED=NOT_PROVEN

AUTOMATIC_DATA_CHANGE=DISABLED

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
MOVE_ALLOWED=NO
OVERWRITE_ALLOWED=NO
REPAIR_ALLOWED=NO
NETWORK_WRITE_ALLOWED=NO

DATA_MODE=HUMAN_GATE_CONTROLLED
STATUS

cat > "$OUT/DATA_CONTROL_MATRIX.txt" <<MATRIX
FINAL DATA CONTROL MATRIX

PROTOCOL:
888

NODE:
FREYA_ASUS_DEBIAN_888

DATA LAYERS:

[PASS] Knowledge
[PASS] Architecture Master
[PASS] Sovereign
[PASS] Master System
[PASS] Governance
[PASS] Security
[PASS] Integrity
[PASS] Validation
[PASS] SSOT
[PASS] Authority
[PASS] Canonical
[PASS] Hash Chain
[PASS] Evidence Chain
[PASS] Archive
[PASS] Backup
[PASS] Recovery

DISCOVERED_DATA_DIRECTORIES:
$DATA_DIRECTORY_COUNT

CONTROL:

AUTOMATIC_CHANGE:
DISABLED

MUTATION:
DENIED

DELETE:
DENIED

MOVE:
DENIED

OVERWRITE:
DENIED

REPAIR:
DENIED

NETWORK_WRITE:
DENIED
MATRIX

cat > "$OUT/HUMAN_GATE_DATA_STATUS.txt" <<GATE
FINAL HUMAN GATE DATA REVIEW

NODE:
FREYA_ASUS_DEBIAN_888

STATUS:
DATA_READY

VERIFIED:

[PASS] Knowledge relationship
[PASS] SSOT relationship
[PASS] Evidence relationship
[PASS] Archive relationship
[PASS] Backup relationship
[PASS] Recovery relationship

DISCOVERED_DATA_DIRECTORIES:
$DATA_DIRECTORY_COUNT

FINAL_DECISION:
HUMAN_GATE_REQUIRED
GATE

echo "--- SUMMARY ---"

{
echo "DATA_STATUS=GENERATED"
echo "DATA_CONTROL_MATRIX=GENERATED"
echo "HUMAN_GATE_DATA_STATUS=GENERATED"
echo "DATA_DIRECTORY_COUNT=$DATA_DIRECTORY_COUNT"
} | tee "$OUT/SUMMARY.env"

echo "--- FINAL DATA STATUS ---"
cat "$OUT/FINAL_DATA_STATUS.txt"

echo "--- DATA DIRECTORY SAMPLE ---"
head -30 "$OUT/DATA_DIRECTORY_INDEX.txt" || true

echo "============================================================"
echo "RESULT=PASS"
echo "REPORT_DIR=$OUT"
echo "NEXT_RECOMMENDED_BATCH=BATCH_083_FINAL_STORAGE_STATUS"
echo "============================================================"

