#!/bin/bash
set -u
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

TARGET="/mnt/c/Users/titangrid.info/Desktop/FREYA_150_FROM_MAC_REVIEW_ONLY – kopija"
ORCH="$TARGET/_FREYA_MULTI_DEVICE_LEARNING"
DAEMON="$TARGET/_FREYA_DAEMON_OUTPUT"
IN="$HOME/FREYA_BUILDER/01_INBOX/FROM_MAC"

mkdir -p "$ORCH/logs" "$ORCH/reports" "$ORCH/registers" "$ORCH/device_nodes" "$ORCH/state"
echo "$$" > "$ORCH/FREYA_MULTI_DEVICE_ORCHESTRATOR.pid"

while true; do
  TS="$(date '+%Y-%m-%d %H:%M:%S')"
  RUN="$(date '+%Y%m%d_%H%M%S')"
  R="$ORCH/reports/MULTI_DEVICE_TICK_$RUN"
  mkdir -p "$R"

  SLOT_COUNT="$(find "$TARGET" -maxdepth 1 -type d -name 'FREYA_SLOT_*' 2>/dev/null | wc -l | tr -d ' ')"
  WRITER_PID="$(cat "$DAEMON/FREYA_WRITER.pid" 2>/dev/null || true)"
  WATCHDOG_PID="$(cat "$DAEMON/FREYA_WRITER_WATCHDOG.pid" 2>/dev/null || true)"

  WRITER_STATUS="DOWN"
  WATCHDOG_STATUS="DOWN"
  [ -n "$WRITER_PID" ] && ps -p "$WRITER_PID" >/dev/null 2>&1 && WRITER_STATUS="ALIVE"
  [ -n "$WATCHDOG_PID" ] && ps -p "$WATCHDOG_PID" >/dev/null 2>&1 && WATCHDOG_STATUS="ALIVE"

  PACKET_STATUS="NO"
  SHA_STATUS="WAITING_FOR_PACKET"
  PKG="FREYA_MAC_DISK_ANDROID_TO_LENOVO_PACKET_20260702_001724.tar.gz"
  SHA="$PKG.sha256"

  if [ -f "$IN/$PKG" ] && [ -f "$IN/$SHA" ]; then
    PACKET_STATUS="YES"
    EXPECTED="$(awk '{print $1}' "$IN/$SHA" 2>/dev/null || true)"
    ACTUAL="$(sha256sum "$IN/$PKG" 2>/dev/null | awk '{print $1}' || true)"
    if [ -n "$EXPECTED" ] && [ -n "$ACTUAL" ] && [ "$EXPECTED" = "$ACTUAL" ]; then
      SHA_STATUS="OK"
    else
      SHA_STATUS="FAIL"
    fi
  fi

  cat > "$R/00_ORCHESTRATOR_STATUS.md" <<STATUS
FREYA MULTI-DEVICE LEARNING ORCHESTRATOR

TIME=$TS
MODE=OBSERVE_LEARN_REPORT_ONLY

ACTIVE DEVICES / NODES:
1. LENOVO_WSL_DELTA=ACTIVE
2. WINDOWS_DESKTOP_REVIEW_LAYER=ACTIVE
3. FREYA_150_SLOTS=ACTIVE
4. WRITER_DAEMON_V2=$WRITER_STATUS
5. WATCHDOG=$WATCHDOG_STATUS
6. MAC_PACKET_GATE=$PACKET_STATUS
7. ANDROID_SOURCE_LAYER=WAITING_THROUGH_MAC_PACKET
8. IPHONE_SOURCE_LAYER=NOT_CONNECTED
9. MSI_SOURCE_LAYER=NOT_CONNECTED

LEARNING_SCOPE:
- read slot status
- read daemon registers
- read inbox packet gate
- create device-node status cards
- create learning ledger

BLOCKS:
UNKNOWN_SCRIPT_RUNTIME=BLOCKED
DELETE=BLOCKED
UNPACK=BLOCKED
NETWORK_ACTION=BLOCKED
HUMAN_GATE=ACTIVE
STATUS

  cat > "$ORCH/device_nodes/LENOVO_WSL_DELTA.md" <<NODE
NODE=LENOVO_WSL_DELTA
STATUS=ACTIVE
ROLE=BUILDER_ORCHESTRATOR
WRITER_DAEMON=$WRITER_STATUS
WATCHDOG=$WATCHDOG_STATUS
LAST_CHECK=$TS
NODE

  cat > "$ORCH/device_nodes/WINDOWS_DESKTOP_LAYER.md" <<NODE
NODE=WINDOWS_DESKTOP_LAYER
STATUS=ACTIVE
TARGET=$TARGET
SLOT_COUNT=$SLOT_COUNT
LAST_CHECK=$TS
NODE

  cat > "$ORCH/device_nodes/MAC_CONTROL_TOWER.md" <<NODE
NODE=MAC_CONTROL_TOWER
STATUS=NOT_CONNECTED_FROM_WINDOWS
MAC_PACKET_RECEIVED=$PACKET_STATUS
SHA_STATUS=$SHA_STATUS
LAST_CHECK=$TS
NODE

  cat > "$ORCH/device_nodes/ANDROID_TERMUX.md" <<NODE
NODE=ANDROID_TERMUX
STATUS=WAITING_THROUGH_MAC_PACKET
ROLE=RELAY_HASH_MANIFEST
LAST_CHECK=$TS
NODE

  cat > "$ORCH/device_nodes/IPHONE_ALPINE.md" <<NODE
NODE=IPHONE_ALPINE
STATUS=NOT_CONNECTED
ROLE=VISIBLE_EVIDENCE_SOURCE
LAST_CHECK=$TS
NODE

  cat > "$ORCH/device_nodes/MSI_BUILDER_OCEAN.md" <<NODE
NODE=MSI_BUILDER_OCEAN
STATUS=NOT_CONNECTED
ROLE=DEEP_KERNEL_SCRIPT_OCEAN
LAST_CHECK=$TS
NODE

  cat > "$R/01_LEARNING_LEDGER.md" <<LEARN
FREYA LEARNING LEDGER

TIME=$TS

LEARNED_NOW:
- 150 Windows Desktop review slots exist.
- V2 writer daemon is $WRITER_STATUS.
- Watchdog is $WATCHDOG_STATUS.
- Mac packet status is $PACKET_STATUS.
- SHA status is $SHA_STATUS.
- No indexing allowed until SHA_OK.
- No unknown script runtime allowed.

NEXT_SAFE_LEARNING:
- keep observing slot logs
- keep packet gate open
- build local index shell only after packet or Human Gate
LEARN

  echo "$TS	ORCHESTRATOR_TICK	SLOTS=$SLOT_COUNT	WRITER=$WRITER_STATUS	WATCHDOG=$WATCHDOG_STATUS	PACKET=$PACKET_STATUS	SHA=$SHA_STATUS" >> "$ORCH/registers/MULTI_DEVICE_LEARNING_TICKS.tsv"

  cat > "$ORCH/FREYA_MULTI_DEVICE_CONTROL_PANEL.md" <<PANEL
FREYA MULTI-DEVICE CONTROL PANEL

LAST_CHECK=$TS
ORCHESTRATOR_PID=$$
TARGET=$TARGET

CURRENT_ACTIVE:
- LENOVO_WSL_DELTA
- WINDOWS_DESKTOP_REVIEW_LAYER
- FREYA_WRITER_DAEMON_V2
- FREYA_WRITER_WATCHDOG
- FREYA_150_SLOT_LAYER

WAITING:
- MAC_PACKET
- ANDROID_THROUGH_MAC
- IPHONE
- MSI

CURRENT_GATE:
PACKET_RECEIVED=$PACKET_STATUS
SHA_STATUS=$SHA_STATUS

RULES:
RUNTIME=BLOCKED
DELETE=BLOCKED
UNPACK=BLOCKED
NETWORK_ACTION=BLOCKED
INDEX_ONLY_AFTER_SHA_OK=YES
HUMAN_GATE=ACTIVE
PANEL

  sleep 90
done
