#!/data/data/com.termux/files/usr/bin/bash
set -e

OUT="FORENSIC_CHECK_STEPS1_25_888.txt"

{
echo "# FORENSIC_CHECK_STEPS1_25_888"
echo "STATUS: STATIC REVIEW ONLY"
echo "DATE: $(date)"
echo

echo "## STEP FILE EXISTENCE"
for f in STEP*.md STEP*.txt; do
  [ -f "$f" ] && echo "FOUND: $f"
done

echo
echo "## SHA256 ALL STEP FILES"
sha256sum STEP*.md STEP*.txt

echo
echo "## FORBIDDEN WORD CHECK"
grep -RniE "LENDER_READY|BANKABLE|SYSTEM_GREEN|FINAL_APPROVED|AUDIT_APPROVED|VERIFIED_FOR_AUDIT|FINANCING_SECURED" STEP*.md STEP*.txt || echo "NO FORBIDDEN TERMS FOUND"

echo
echo "## REQUIRED BLOCKER LANGUAGE CHECK"
grep -RniE "NOT AUTHORIZED|HUMAN REVIEW REQUIRED|PENDING EXTERNAL VERIFICATION|NOT VERIFIED|NOT OBTAINED" STEP*.md STEP*.txt | head -100

echo
echo "## CORRECTED DOCX MEDIA CHECK"
cat 05_CONTROLLED_LOGO_EMBEDDING_WORKFLOW/validation/corrected_docx_logo_media_check.txt 2>/dev/null || echo "DOCX MEDIA CHECK FILE MISSING"

echo
echo "## DWG HASH CHECK"
grep -i "\.dwg$" 06_DWG_TECHNICAL_EVIDENCE_INDEXING/dwg_candidate_sha256.txt 2>/dev/null || echo "DWG HASH MISSING"

echo
echo "## CONSULTANT HANDOFF HASH REGISTER"
cat STEP25_CONSULTANT_HANDOFF_HASH_REGISTER.txt 2>/dev/null || echo "HANDOFF HASH REGISTER MISSING"

echo
echo "## FINAL FORENSIC POSITION"
echo "STEPS 1-25 STATIC PACKAGE CHECKED."
echo "NO SUBMISSION AUTHORIZED."
echo "NO LENDER READY CLAIM AUTHORIZED."
echo "HUMAN / LEGAL / ENGINEERING REVIEW REQUIRED."
} > "$OUT"

sha256sum "$OUT"
