#!/bin/bash
D5="/home/titangridmne/FREYA_BUILDER/99_DAEMON_RUN_GATE/DAEMON_005_SAFE_EXTRACT_GATE_PREVIEW"
DROP="/mnt/c/Users/titangrid.info/Desktop/FREYA_LENOVO_RECEIVER_DROPZONES/FROM_MAC"
PKT="$DROP/FREYA_MAC_DISK_ANDROID_TO_LENOVO_PACKET_20260702_001724.tar.gz"
EXPECTED="3d74b850a770dac0ef8543f2b2ef3b8a9cf4bb0f0eb4133f4028812f170df5e9"

while true; do
  TS="$(date '+%Y%m%d_%H%M%S')"
  LIST="$D5/TAR_LIST_CURRENT.txt"
  PREVIEW="$D5/SAFE_EXTRACT_GATE_PREVIEW.md"

  PKT_STATUS="NO"
  SHA_STATUS="NOT_AVAILABLE"
  PATH_TRAVERSAL_COUNT="NA"
  ABSOLUTE_PATH_COUNT="NA"
  RUNTIME_FILE_HINT_COUNT="NA"
  EXTRACT_GATE="BLOCKED"

  if [ -f "$PKT" ]; then
    PKT_STATUS="YES"
    ACTUAL="$(sha256sum "$PKT" | awk '{print $1}')"
    [ "$ACTUAL" = "$EXPECTED" ] && SHA_STATUS="OK" || SHA_STATUS="FAIL"

    tar -tzf "$PKT" > "$LIST" 2>/dev/null

    PATH_TRAVERSAL_COUNT="$(grep -E '(^|/)\.\.(/|$)' "$LIST" | wc -l | tr -d ' ')"
    ABSOLUTE_PATH_COUNT="$(grep -E '^/' "$LIST" | wc -l | tr -d ' ')"
    RUNTIME_FILE_HINT_COUNT="$(grep -Ei '\.(sh|ps1|py|exe|bat|cmd|js|vbs|jar|dll|so)$' "$LIST" | wc -l | tr -d ' ')"

    if [ "$SHA_STATUS" = "OK" ] && [ "$PATH_TRAVERSAL_COUNT" = "0" ] && [ "$ABSOLUTE_PATH_COUNT" = "0" ]; then
      EXTRACT_GATE="READY_FOR_HUMAN_REVIEW_ONLY_EXTRACT"
    else
      EXTRACT_GATE="BLOCKED"
    fi
  fi

  cat > "$PREVIEW" <<REPORT
DAEMON_005_SAFE_EXTRACT_GATE_PREVIEW

LAST_HEARTBEAT=$TS
STATUS=ACTIVE
MODE=PREVIEW_ONLY
UNPACK=NO
OLD_SCRIPT_RUNTIME=NO
HUMAN_GATE=ACTIVE

PACKET_PRESENT=$PKT_STATUS
SHA_STATUS=$SHA_STATUS
PATH_TRAVERSAL_COUNT=$PATH_TRAVERSAL_COUNT
ABSOLUTE_PATH_COUNT=$ABSOLUTE_PATH_COUNT
RUNTIME_FILE_HINT_COUNT=$RUNTIME_FILE_HINT_COUNT

DECISION:
EXTRACT_GATE=$EXTRACT_GATE
EXTRACT_NOW=NO
RUNTIME_ALLOWED=NO

NEXT_ALLOWED:
IF EXTRACT_GATE=READY_FOR_HUMAN_REVIEW_ONLY_EXTRACT THEN CREATE_REVIEW_ONLY_EXTRACT_FOLDER
REPORT

  cp "$PREVIEW" "$D5/HEARTBEAT.md"
  echo "$TS DAEMON_005 heartbeat extract-gate-preview=$EXTRACT_GATE" >> "$D5/daemon_005.log"
  sleep 30
done
