#!/bin/bash
set -u
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

TARGET="/mnt/c/Users/titangrid.info/Desktop/FREYA_150_FROM_MAC_REVIEW_ONLY – kopija"
DAEMON="$TARGET/_FREYA_DAEMON_OUTPUT"
PIDF="$DAEMON/FREYA_WRITER.pid"
IN="$HOME/FREYA_BUILDER/01_INBOX/FROM_MAC"

PKG="FREYA_MAC_DISK_ANDROID_TO_LENOVO_PACKET_20260702_001724.tar.gz"
SHA="$PKG.sha256"

mkdir -p "$DAEMON/logs" "$DAEMON/reports" "$DAEMON/registers" "$DAEMON/state" "$DAEMON/errors"
echo "$$" > "$PIDF"
echo "V2_STARTED_AT=$(date '+%Y-%m-%d %H:%M:%S')" > "$DAEMON/state/V2_STATUS.env"

while true; do
  TS="$(date '+%Y-%m-%d %H:%M:%S')"
  RUN="$(date '+%Y%m%d_%H%M%S')"
  REPORT_DIR="$DAEMON/reports/V2_TICK_$RUN"
  mkdir -p "$REPORT_DIR"

  SLOT_COUNT="$(find "$TARGET" -maxdepth 1 -type d -name 'FREYA_SLOT_*' 2>/dev/null | wc -l | tr -d ' ')"

  PACKET_STATUS="NO"
  SHA_STATUS="WAITING_FOR_PACKET"
  EXPECTED=""
  ACTUAL=""

  if [ -f "$IN/$PKG" ] && [ -f "$IN/$SHA" ]; then
    PACKET_STATUS="YES"
    EXPECTED="$(awk '{print $1}' "$IN/$SHA" 2>/dev/null || true)"
    ACTUAL="$(sha256sum "$IN/$PKG" 2>/dev/null | awk '{print $1}' || true)"

    if [ -n "$EXPECTED" ] && [ -n "$ACTUAL" ] && [ "$EXPECTED" = "$ACTUAL" ]; then
      SHA_STATUS="OK"
      echo "$TS SHA_OK $ACTUAL" > "$DAEMON/state/READY_FOR_INDEX_ONLY.flag"
    else
      SHA_STATUS="FAIL"
      rm -f "$DAEMON/state/READY_FOR_INDEX_ONLY.flag" 2>/dev/null || true
      echo "$TS SHA_FAIL EXPECTED=$EXPECTED ACTUAL=$ACTUAL" >> "$DAEMON/errors/SHA_ERRORS.tsv"
    fi
  else
    rm -f "$DAEMON/state/READY_FOR_INDEX_ONLY.flag" 2>/dev/null || true
  fi

  cat > "$REPORT_DIR/D000_MASTER.md" <<MASTER
FREYA WRITER DAEMON V2

TIME=$TS
TARGET=$TARGET
PID=$$
MODE=WRITE_REPORTS_ONLY
SLOT_COUNT=$SLOT_COUNT
PACKET_RECEIVED=$PACKET_STATUS
SHA_STATUS=$SHA_STATUS
RUNTIME=BLOCKED
DELETE=BLOCKED
UNPACK=BLOCKED
HUMAN_GATE=ACTIVE
MASTER

  cat > "$REPORT_DIR/D001_PACKET_GATE.md" <<PACKET
D001 PACKET GATE

INBOX=$IN
PACKET=$PKG
SHA_FILE=$SHA
PACKET_RECEIVED=$PACKET_STATUS
RULE=NO_INDEX_UNTIL_SHA_OK
PACKET

  cat > "$REPORT_DIR/D002_SHA_GATE.md" <<SHAGATE
D002 SHA GATE

EXPECTED=$EXPECTED
ACTUAL=$ACTUAL
SHA_STATUS=$SHA_STATUS
FALSE_EMPTY_SHA_OK_BLOCKED=YES
SHAGATE

  cat > "$REPORT_DIR/D003_SLOT_INTEGRITY.md" <<SLOTS
D003 SLOT INTEGRITY

EXPECTED_SLOTS=150
ACTUAL_SLOTS=$SLOT_COUNT
STATUS=$([ "$SLOT_COUNT" = "150" ] && echo OK || echo CHECK_NEEDED)
SLOTS

  cat > "$REPORT_DIR/D004_HUMAN_GATE.md" <<HG
D004 HUMAN GATE

RUNTIME=BLOCKED
UNKNOWN_SCRIPT_EXECUTION=BLOCKED
DELETE=BLOCKED
UNPACK=BLOCKED
OVERWRITE_CORE=BLOCKED
INDEX_ONLY_AFTER_SHA_OK=YES
HG

  cat > "$REPORT_DIR/D005_NEXT_ALLOWED.md" <<NEXT
D005 NEXT ALLOWED

IF_SHA_OK=REGISTER_PACKET_AND_INDEX_ONLY
IF_SHA_NOT_OK=WAIT_FOR_PACKET_OR_REPAIR_TRANSFER
CURRENT_SHA_STATUS=$SHA_STATUS
NEXT

  # update each slot
  for SLOT in "$TARGET"/FREYA_SLOT_*; do
    [ -d "$SLOT" ] || continue
    SLOT_NAME="$(basename "$SLOT")"

    cat > "$SLOT/CURRENT_SLOT_STATUS.md" <<SLOTSTATUS
FREYA SLOT STATUS — V2

SLOT=$SLOT_NAME
LAST_TICK=$TS
WRITER_DAEMON=ACTIVE_V2
MAC_PACKET_RECEIVED=$PACKET_STATUS
SHA_STATUS=$SHA_STATUS
RUNTIME=BLOCKED
DELETE=BLOCKED
UNPACK=BLOCKED
HUMAN_GATE=ACTIVE
NEXT_ALLOWED=WAIT_FOR_SHA_OK_THEN_INDEX_ONLY
SLOTSTATUS

    echo "$TS	ACTIVE_V2	$SLOT_NAME	PACKET=$PACKET_STATUS	SHA=$SHA_STATUS	RUNTIME_BLOCKED	DELETE_BLOCKED	UNPACK_BLOCKED" >> "$SLOT/SLOT_DAEMON_LOG.tsv"
  done

  echo "$TS	V2_TICK_OK	PID=$$	SLOTS=$SLOT_COUNT	PACKET=$PACKET_STATUS	SHA=$SHA_STATUS	REPORT=$REPORT_DIR" >> "$DAEMON/registers/FREYA_WRITER_TICKS.tsv"
  echo "$TS	PACKET=$PACKET_STATUS	SHA=$SHA_STATUS	EXPECTED=$EXPECTED	ACTUAL=$ACTUAL" >> "$DAEMON/registers/FREYA_PACKET_GATE.tsv"

  sleep 120
done
