#!/bin/bash
set -u
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

CORE="$HOME/FREYA_BUILDER/00_LENOVO_MASTER_RECEIVER"
INBOX="$HOME/FREYA_BUILDER/01_INBOX"
REG="$HOME/FREYA_BUILDER/02_REGISTERS"
HG="$HOME/FREYA_BUILDER/04_HUMAN_GATE"
DROP="/mnt/c/Users/titangrid.info/Desktop/FREYA_LENOVO_RECEIVER_DROPZONES"
PANEL="/mnt/c/Users/titangrid.info/Desktop/FREYA_LENOVO_MASTER_RECEIVER_PANEL"

mkdir -p "$CORE/logs" "$CORE/state" "$CORE/reports" "$REG" "$HG" "$PANEL"
echo "$$" > "$CORE/LENOVO_MASTER_RECEIVER.pid"

while true; do
  TS="$(date '+%Y-%m-%d %H:%M:%S')"
  RUN="$(date '+%Y%m%d_%H%M%S')"
  OUT="$CORE/reports/RECEIVER_TICK_$RUN"
  CURRENT="$REG/LENOVO_MASTER_RECEIVER_CURRENT.tsv"
  LEDGER="$REG/LENOVO_MASTER_RECEIVER_LEDGER.tsv"
  mkdir -p "$OUT"

  {
    echo -e "TIME\tSOURCE\tLOCATION_TYPE\tPATH\tSIZE_BYTES\tACTUAL_SHA256\tEXPECTED_SHA256\tSHA_STATUS\tDECISION"
  } > "$CURRENT"

  scan_source() {
    SRC="$1"
    LOC_TYPE="$2"
    DIR="$3"

    [ -d "$DIR" ] || return 0

    find "$DIR" -maxdepth 1 -type f ! -name "*.sha256" 2>/dev/null | while read -r FILE; do
      SIZE="$(stat -c '%s' "$FILE" 2>/dev/null || wc -c < "$FILE" 2>/dev/null || echo 0)"
      ACTUAL="$(sha256sum "$FILE" 2>/dev/null | awk '{print $1}' || true)"
      EXPECTED=""
      SHA_STATUS="NO_SHA_FILE_HOLD"
      DECISION="HOLD_REGISTER_ONLY"

      if [ -f "$FILE.sha256" ]; then
        EXPECTED="$(awk '{print $1}' "$FILE.sha256" 2>/dev/null || true)"
      fi

      if [ -n "$EXPECTED" ] && [ -n "$ACTUAL" ] && [ "$EXPECTED" = "$ACTUAL" ]; then
        SHA_STATUS="OK"
        DECISION="READY_FOR_HUMAN_GATE_INDEX_ONLY"
      elif [ -n "$EXPECTED" ] || [ -n "$ACTUAL" ]; then
        if [ -f "$FILE.sha256" ]; then
          SHA_STATUS="FAIL"
          DECISION="STOP_REPAIR_SOURCE_OR_RETRANSFER"
        fi
      fi

      echo -e "$TS\t$SRC\t$LOC_TYPE\t$FILE\t$SIZE\t$ACTUAL\t$EXPECTED\t$SHA_STATUS\t$DECISION" >> "$CURRENT"
      echo -e "$TS\t$SRC\t$LOC_TYPE\t$FILE\t$SIZE\t$ACTUAL\t$EXPECTED\t$SHA_STATUS\t$DECISION" >> "$LEDGER"
    done
  }

  for SRC in FROM_MAC FROM_ANDROID FROM_IPHONE FROM_MSI FROM_EXTERNAL_DISK FROM_WINDOWS_DESKTOP_DROP; do
    scan_source "$SRC" "WSL_INBOX" "$INBOX/$SRC"
    scan_source "$SRC" "WINDOWS_DROPZONE" "$DROP/$SRC"
  done

  TOTAL_FILES="$(($(wc -l < "$CURRENT") - 1))"
  SHA_OK_COUNT="$(awk -F'\t' 'NR>1 && $8=="OK"{c++} END{print c+0}' "$CURRENT")"
  SHA_FAIL_COUNT="$(awk -F'\t' 'NR>1 && $8=="FAIL"{c++} END{print c+0}' "$CURRENT")"
  HOLD_COUNT="$(awk -F'\t' 'NR>1 && $8!="OK"{c++} END{print c+0}' "$CURRENT")"

  cat > "$OUT/00_LENOVO_MASTER_RECEIVER_STATUS.md" <<STATUS
FREYA LENOVO MASTER RECEIVER

TIME=$TS
PID=$$
ROLE=LENOVO_RECEIVES_ALL_DEVICES
MODE=REGISTER_HASH_GATE_ONLY

COUNTS:
TOTAL_FILES_SEEN=$TOTAL_FILES
SHA_OK_COUNT=$SHA_OK_COUNT
SHA_FAIL_COUNT=$SHA_FAIL_COUNT
HOLD_COUNT=$HOLD_COUNT

RULES:
NO_DELETE=YES
NO_MOVE=YES
NO_UNPACK=YES
NO_UNKNOWN_SCRIPT_RUNTIME=YES
EMPTY_SHA_OK_BLOCKED=YES
HUMAN_GATE=ACTIVE

NEXT_ALLOWED:
- If SHA_OK exists: Human review, then index-only.
- If no SHA: create/obtain SHA sidecar.
- If SHA_FAIL: retransfer or repair source.
STATUS

  cat > "$PANEL/LENOVO_MASTER_RECEIVER_PANEL.md" <<PANEL
FREYA LENOVO MASTER RECEIVER PANEL

LAST_TICK=$TS
PID=$$
ROLE=MASTER_RECEIVER_FOR_ALL_DEVICES

INBOXES:
- $INBOX/FROM_MAC
- $INBOX/FROM_ANDROID
- $INBOX/FROM_IPHONE
- $INBOX/FROM_MSI
- $INBOX/FROM_EXTERNAL_DISK
- $INBOX/FROM_WINDOWS_DESKTOP_DROP

WINDOWS_DROPZONES:
- $DROP/FROM_MAC
- $DROP/FROM_ANDROID
- $DROP/FROM_IPHONE
- $DROP/FROM_MSI
- $DROP/FROM_EXTERNAL_DISK
- $DROP/FROM_WINDOWS_DESKTOP_DROP

CURRENT_COUNTS:
TOTAL_FILES_SEEN=$TOTAL_FILES
SHA_OK_COUNT=$SHA_OK_COUNT
SHA_FAIL_COUNT=$SHA_FAIL_COUNT
HOLD_COUNT=$HOLD_COUNT

CURRENT_REGISTER:
$CURRENT

RULES:
NO_DELETE=YES
NO_MOVE=YES
NO_UNPACK=YES
NO_UNKNOWN_SCRIPT_RUNTIME=YES
INDEX_ONLY_AFTER_SHA_OK_AND_HUMAN_GATE=YES
HUMAN_GATE=ACTIVE
PANEL

  cat > "$HG/LENOVO_MASTER_RECEIVER_HUMAN_GATE.md" <<HGSTATUS
LENOVO MASTER RECEIVER HUMAN GATE

LAST_TICK=$TS

APPROVALS:
DELETE_APPROVED=NO
MOVE_APPROVED=NO
UNPACK_APPROVED=NO
UNKNOWN_SCRIPT_RUNTIME_APPROVED=NO
INDEX_APPROVED_ONLY_AFTER_SHA_OK=YES

CURRENT:
TOTAL_FILES_SEEN=$TOTAL_FILES
SHA_OK_COUNT=$SHA_OK_COUNT
SHA_FAIL_COUNT=$SHA_FAIL_COUNT
HOLD_COUNT=$HOLD_COUNT

STATUS=LENOVO_RECEIVER_ACTIVE_REGISTER_HASH_ONLY
HGSTATUS

  sleep 90
done
