#!/bin/bash
set -u
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"

TARGET="/mnt/c/Users/titangrid.info/Desktop/FREYA_150_FROM_MAC_REVIEW_ONLY – kopija"
DAEMON="$TARGET/_FREYA_DAEMON_OUTPUT"
PIDF="$DAEMON/FREYA_WRITER.pid"
SCRIPT="$DAEMON/FREYA_WRITER_V2.sh"
WATCH_PIDF="$DAEMON/FREYA_WRITER_WATCHDOG.pid"

mkdir -p "$DAEMON/logs" "$DAEMON/registers" "$DAEMON/state"
echo "$$" > "$WATCH_PIDF"

while true; do
  TS="$(date '+%Y-%m-%d %H:%M:%S')"
  STATUS="UNKNOWN"

  PID="$(cat "$PIDF" 2>/dev/null || true)"

  if [ -n "$PID" ] && ps -p "$PID" >/dev/null 2>&1; then
    STATUS="WRITER_ALIVE"
  else
    STATUS="WRITER_RESTARTED"
    nohup "$SCRIPT" >> "$DAEMON/logs/FREYA_WRITER_V2.log" 2>&1 &
    NEWPID=$!
    echo "$NEWPID" > "$PIDF"
    PID="$NEWPID"
  fi

  cat > "$DAEMON/FREYA_DAEMON_CONTROL_PANEL.md" <<PANEL
FREYA DAEMON CONTROL PANEL

LAST_CHECK=$TS
WATCHDOG_PID=$$
WRITER_PID=$PID
WRITER_STATUS=$STATUS

TARGET=$TARGET

ACTIVE_LAYER:
- FREYA_WRITER_DAEMON_V2
- FREYA_WRITER_WATCHDOG

RULES:
UNKNOWN_SCRIPT_RUNTIME=BLOCKED
DELETE=BLOCKED
UNPACK=BLOCKED
INDEX_ONLY_AFTER_SHA_OK=YES
HUMAN_GATE=ACTIVE

MAC_PACKET_STATUS:
WAITING_FOR_PACKET
PANEL

  echo "$TS	WATCHDOG_OK	WRITER_PID=$PID	STATUS=$STATUS" >> "$DAEMON/registers/FREYA_WATCHDOG_TICKS.tsv"

  sleep 60
done
