#!/usr/bin/env bash

set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 047"
echo " FINAL HUMAN APPROVAL RECORD — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
ROOT="/mnt/c/FREYA_ASUS_NODE_888"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_047_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=047"
echo "MODE=READ_ONLY_FINAL_HUMAN_APPROVAL_RECORD"
echo "ROOT=$ROOT"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"


: > "$OUT/FINAL_APPROVAL_RECORD.txt"
: > "$OUT/GOVERNANCE_CHAIN_RECORD.txt"
: > "$OUT/HUMAN_DECISION_REQUIRED.txt"


cat > "$OUT/FINAL_APPROVAL_RECORD.txt" <<RECORD
PROTOCOL=888

FINAL_SCOPE=ASUS_DEBIAN_NODE

SSOT_STATUS=FOUND
AUTHORITY_STATUS=FOUND
CANONICAL_STATUS=FOUND
HASH_CHAIN_STATUS=FOUND
EVIDENCE_CHAIN_STATUS=FOUND

FINAL_REVIEW_PACKAGE=READY
FINAL_CERTIFICATION_REVIEW=READY
HUMAN_GATE_PACKAGE=READY

ACTIVE_CONFLICT=NOT_PROVEN
LIVE_REPAIR_REQUIRED=NOT_PROVEN

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
REPAIR_ALLOWED=NO

FINAL_DECISION=HUMAN_GATE_REQUIRED
RECORD


find "$REPORT_ROOT" \
-maxdepth 1 \
-type d \
-name "BATCH_*" \
2>/dev/null \
| sort \
> "$OUT/GOVERNANCE_CHAIN_RECORD.txt"


cat > "$OUT/HUMAN_DECISION_REQUIRED.txt" <<DECISION
HUMAN GATE FINAL DECISION REQUIRED

PROTOCOL:
888

SYSTEM:
ASUS_DEBIAN_NODE

REVIEW STATUS:
READY

VERIFIED DOMAINS:

[PASS] SSOT
[PASS] AUTHORITY
[PASS] CANONICAL
[PASS] HASH_CHAIN
[PASS] EVIDENCE_CHAIN
[PASS] FINAL_REVIEW_PACKAGE
[PASS] CERTIFICATION_REVIEW

WARNINGS:

- Historical/archive conflict signals require human interpretation
- No automatic mutation permitted

OPERATOR ACTION:
REQUIRED

MUTATION:
DENIED

DELETE:
DENIED

REPAIR:
DENIED
DECISION


echo "--- SUMMARY ---"

{
echo "APPROVAL_RECORD_STATUS=CREATED"
echo "GOVERNANCE_CHAIN_COUNT=$(wc -l < "$OUT/GOVERNANCE_CHAIN_RECORD.txt")"
echo "HUMAN_DECISION_STATUS=REQUIRED"
} | tee "$OUT/SUMMARY.env"


echo "--- FINAL APPROVAL RECORD ---"
cat "$OUT/FINAL_APPROVAL_RECORD.txt"


echo "============================================================"
echo "RESULT=PASS"
echo "REPORT_DIR=$OUT"
echo "NEXT_RECOMMENDED_BATCH=BATCH_048_FINAL_ARCHIVE_CERTIFICATION"
echo "============================================================"

