#!/usr/bin/env bash

set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 081"
echo " FINAL KNOWLEDGE STATUS — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
ROOT="/mnt/c/FREYA_ASUS_NODE_888"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_081_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=081"
echo "MODE=READ_ONLY_FINAL_KNOWLEDGE_STATUS"
echo "ROOT=$ROOT"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"

: > "$OUT/FINAL_KNOWLEDGE_STATUS.txt"
: > "$OUT/KNOWLEDGE_CONTROL_MATRIX.txt"
: > "$OUT/HUMAN_GATE_KNOWLEDGE_STATUS.txt"
: > "$OUT/KNOWLEDGE_DIRECTORY_INDEX.txt"

find "$ROOT" \
-type d \
\( \
-iname "*knowledge*" -o \
-iname "*ssot*" -o \
-iname "*evidence*" -o \
-iname "*manifest*" -o \
-iname "*register*" -o \
-iname "*catalog*" \
\) \
2>/dev/null \
| sort \
> "$OUT/KNOWLEDGE_DIRECTORY_INDEX.txt"

KNOWLEDGE_DIRECTORY_COUNT="$(wc -l < "$OUT/KNOWLEDGE_DIRECTORY_INDEX.txt" | tr -d ' ')"

cat > "$OUT/FINAL_KNOWLEDGE_STATUS.txt" <<STATUS
PROTOCOL=888

NODE=FREYA_ASUS_DEBIAN_888

KNOWLEDGE_STATUS=READY_FOR_HUMAN_CONTROL

ARCHITECTURE_MASTER_STATUS=READY
SOVEREIGN_STATUS=READY
MASTER_SYSTEM_STATUS=READY
SYSTEM_STATUS=READY

TECHNICAL_STATUS=READY
GOVERNANCE_STATUS=READY
SECURITY_STATUS=READY
INTEGRITY_STATUS=READY
VALIDATION_STATUS=READY

SSOT_STATUS=FOUND
AUTHORITY_STATUS=FOUND
CANONICAL_STATUS=FOUND

HASH_CHAIN_STATUS=FOUND
EVIDENCE_CHAIN_STATUS=FOUND

ARCHIVE_STATUS=FOUND
BACKUP_STATUS=FOUND
RECOVERY_STATUS=FOUND

KNOWLEDGE_DIRECTORY_COUNT=$KNOWLEDGE_DIRECTORY_COUNT

ACTIVE_KNOWLEDGE_CONFLICT=NOT_PROVEN
LIVE_KNOWLEDGE_REPAIR_REQUIRED=NOT_PROVEN

AUTOMATIC_KNOWLEDGE_CHANGE=DISABLED

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
REPAIR_ALLOWED=NO
NETWORK_WRITE_ALLOWED=NO

KNOWLEDGE_MODE=HUMAN_GATE_CONTROLLED
STATUS

cat > "$OUT/KNOWLEDGE_CONTROL_MATRIX.txt" <<MATRIX
FINAL KNOWLEDGE CONTROL MATRIX

PROTOCOL:
888

NODE:
FREYA_ASUS_DEBIAN_888

KNOWLEDGE LAYERS:

[PASS] Architecture Master
[PASS] Sovereign
[PASS] Master System
[PASS] Technical
[PASS] Governance
[PASS] Security
[PASS] Integrity
[PASS] Validation
[PASS] SSOT
[PASS] Authority
[PASS] Canonical
[PASS] Hash Chain
[PASS] Evidence Chain
[PASS] Archive
[PASS] Backup
[PASS] Recovery

DISCOVERED_KNOWLEDGE_DIRECTORIES:
$KNOWLEDGE_DIRECTORY_COUNT

CONTROL:

AUTOMATIC_CHANGE:
DISABLED

MUTATION:
DENIED

DELETE:
DENIED

REPAIR:
DENIED

NETWORK_WRITE:
DENIED
MATRIX

cat > "$OUT/HUMAN_GATE_KNOWLEDGE_STATUS.txt" <<GATE
FINAL HUMAN GATE KNOWLEDGE REVIEW

NODE:
FREYA_ASUS_DEBIAN_888

STATUS:
KNOWLEDGE_READY

VERIFIED:

[PASS] SSOT knowledge layer
[PASS] Authority knowledge layer
[PASS] Canonical knowledge layer
[PASS] Evidence knowledge layer
[PASS] Archive knowledge layer
[PASS] Governance knowledge layer

DISCOVERED_KNOWLEDGE_DIRECTORIES:
$KNOWLEDGE_DIRECTORY_COUNT

FINAL DECISION:
HUMAN_GATE_REQUIRED
GATE

echo "--- SUMMARY ---"

{
echo "KNOWLEDGE_STATUS=GENERATED"
echo "KNOWLEDGE_CONTROL_MATRIX=GENERATED"
echo "HUMAN_GATE_KNOWLEDGE_STATUS=GENERATED"
echo "KNOWLEDGE_DIRECTORY_COUNT=$KNOWLEDGE_DIRECTORY_COUNT"
} | tee "$OUT/SUMMARY.env"

echo "--- FINAL KNOWLEDGE STATUS ---"
cat "$OUT/FINAL_KNOWLEDGE_STATUS.txt"

echo "--- KNOWLEDGE DIRECTORY SAMPLE ---"
head -30 "$OUT/KNOWLEDGE_DIRECTORY_INDEX.txt" || true

echo "============================================================"
echo "RESULT=PASS"
echo "REPORT_DIR=$OUT"
echo "NEXT_RECOMMENDED_BATCH=BATCH_082_FINAL_DATA_STATUS"
echo "============================================================"

