#!/usr/bin/env bash
set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 098R4R2"
echo " CORRECTED METADATA PILOT CANARY PLAN — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"

ROOT="/mnt/c/FREYA_ASUS_NODE_888"
AGENT_PARENT="$ROOT/03_AGENTS_ACTIVE"
PACKAGE="VALIDATED_PENDING_RUNTIME"
AGENT_ROOT="$AGENT_PARENT/$PACKAGE"

REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_098R4R2_$START_UTC"

TARGET="$AGENT_ROOT/05c0204f9c0a_agent_discovery.py"

EXPECTED_AGENT_ID="AGENT-dc77a383ab7dd347cc2d248d"
EXPECTED_RELATIVE_PATH="05c0204f9c0a_agent_discovery.py"
EXPECTED_SHA256="05c0204f9c0aba288d4dc8e74d171fe5ad78db39f743d0a53a78f4d5a581cc72"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=098R4R2"
echo "MODE=READ_ONLY_CORRECTED_METADATA_PILOT_CANARY_PLAN"
echo "START_UTC=$START_UTC"
echo "AGENT_PARENT=$AGENT_PARENT"
echo "PACKAGE=$PACKAGE"
} > "$OUT/BATCH.env"

: > "$OUT/PREFLIGHT.txt"
: > "$OUT/PACKAGE_BINDING_PLAN.txt"
: > "$OUT/CANARY_EXECUTION_CONTRACT.txt"
: > "$OUT/FINAL_STATUS.txt"

echo "===== PREFLIGHT ====="

FILES=(
  "$AGENT_ROOT/agent_descriptor.py"
  "$AGENT_ROOT/agent_registry.py"
  "$AGENT_ROOT/evidence_complete_producer.py"
  "$AGENT_ROOT/ea4106a2d52a_metadata_agent_pilot.py"
  "$AGENT_ROOT/4fae0850626f_agent_validation_engine.py"
  "$TARGET"
)

FAIL_COUNT=0

for f in "${FILES[@]}"; do
    if [[ -f "$f" ]]; then
        echo "FILE=$f"
        echo "STATUS=PRESENT"
        echo "SHA256=$(sha256sum "$f" | awk '{print $1}')"
    else
        echo "FILE=$f"
        echo "STATUS=MISSING"
        FAIL_COUNT=$((FAIL_COUNT + 1))
    fi
    echo
done | tee "$OUT/PREFLIGHT.txt"

ACTUAL_TARGET_HASH="$(
  sha256sum "$TARGET" 2>/dev/null |
  awk '{print $1}'
)"

if [[ "$ACTUAL_TARGET_HASH" == "$EXPECTED_SHA256" ]]; then
    TARGET_HASH_STATUS="PASS"
else
    TARGET_HASH_STATUS="FAIL"
    FAIL_COUNT=$((FAIL_COUNT + 1))
fi

cat > "$OUT/PACKAGE_BINDING_PLAN.txt" <<PLAN
PACKAGE_IMPORT_MODEL=PROVEN

RUNTIME_PYTHONPATH=$AGENT_PARENT
PACKAGE=$PACKAGE

IMPORT_1=$PACKAGE.agent_descriptor
IMPORT_2=$PACKAGE.agent_registry
IMPORT_3=$PACKAGE.evidence_complete_producer
IMPORT_4=$PACKAGE.ea4106a2d52a_metadata_agent_pilot
IMPORT_5=$PACKAGE.4fae0850626f_agent_validation_engine

TOP_LEVEL_AGENT_REGISTRY_IMPORT=DENY
TOP_LEVEL_VALIDATOR_IMPORT=DENY

PERSISTENT_PYTHONPATH_CHANGE=DENY
TEMPORARY_PROCESS_PYTHONPATH_ONLY=YES

SOURCE_FILE_CHANGE_REQUIRED=NO
MODULE_CONTENT_CHANGE_REQUIRED=NO
PLAN

cat > "$OUT/CANARY_EXECUTION_CONTRACT.txt" <<CONTRACT
TARGET_AGENT_ID=$EXPECTED_AGENT_ID
TARGET_RELATIVE_PATH=$EXPECTED_RELATIVE_PATH
TARGET_SHA256=$EXPECTED_SHA256

EXECUTION_SCOPE=ONE_AGENT_ONE_METADATA_PILOT_CALL

STEP_1=VERIFY_TARGET_HASH
STEP_2=BUILD_AGENT_DESCRIPTOR
STEP_3=VALIDATE_DESCRIPTOR
STEP_4=BUILD_SINGLE_AGENT_REGISTRY
STEP_5=VALIDATE_REGISTRY
STEP_6=BUILD_IN_MEMORY_EVIDENCE_COMPLETE_RECORD
STEP_7=CALL_RUN_METADATA_PILOT_EXACTLY_ONCE
STEP_8=VERIFY_RESULT_AGENT_ID
STEP_9=VERIFY_RESULT_SHA256
STEP_10=VERIFY_RESULT_STATUS_PASS_METADATA_CONTROL_PLANE

NETWORK_ALLOWED=NO
FILE_WRITE_ALLOWED=NO
SERVICE_START_ALLOWED=NO
PACKAGE_INSTALL_ALLOWED=NO
EXTERNAL_SEND_ALLOWED=NO
DELETE_ALLOWED=NO
MOVE_ALLOWED=NO
RENAME_ALLOWED=NO
FORMAT_ALLOWED=NO

PYTHONDONTWRITEBYTECODE=1
PYTHONNOUSERSITE=1

HUMAN_GATE_REQUIRED_BEFORE_EXECUTION=YES
CONTRACT

if [[ "$FAIL_COUNT" -eq 0 &&
      "$TARGET_HASH_STATUS" == "PASS" ]]; then
    PLAN_STATUS="READY_FOR_HUMAN_GATE"
else
    PLAN_STATUS="HOLD"
fi

cat > "$OUT/FINAL_STATUS.txt" <<STATUS
PROTOCOL=888
NODE=FREYA_ASUS_DEBIAN_888

CORRECTED_METADATA_PILOT_CANARY_PLAN=COMPLETE

COMPONENT_FAIL_COUNT=$FAIL_COUNT
TARGET_HASH_STATUS=$TARGET_HASH_STATUS

PACKAGE_IMPORT_MODEL=PROVEN
SOURCE_REPAIR_REQUIRED=NO
MODULE_CONTENT_CHANGE_REQUIRED=NO

PLAN_STATUS=$PLAN_STATUS

TARGET_FUNCTION_EXECUTED=NO
METADATA_PILOT_EXECUTED=NO
AGENT_TASK_EXECUTED=NO

FILE_MUTATION_EXECUTED=NO
NETWORK_EXECUTED=NO
PACKAGE_INSTALL_EXECUTED=NO
SERVICE_START_EXECUTED=NO

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
REPAIR_ALLOWED=NO

HUMAN_GATE_REQUIRED=YES
MODE=HUMAN_GATE_CONTROLLED
STATUS

echo
echo "--- PACKAGE BINDING PLAN ---"
cat "$OUT/PACKAGE_BINDING_PLAN.txt"

echo
echo "--- CANARY EXECUTION CONTRACT ---"
cat "$OUT/CANARY_EXECUTION_CONTRACT.txt"

echo
echo "--- FINAL STATUS ---"
cat "$OUT/FINAL_STATUS.txt"

echo "============================================================"

if [[ "$PLAN_STATUS" == "READY_FOR_HUMAN_GATE" ]]; then
    echo "RESULT=HOLD"
    echo "BLOCKER=HUMAN_GATE_APPROVAL_REQUIRED_FOR_CORRECTED_METADATA_PILOT_CANARY"
    echo "NEXT_RECOMMENDED_BATCH=BATCH_098R4R3_CORRECTED_METADATA_PILOT_CANARY_HUMAN_GATE"
else
    echo "RESULT=HOLD"
    echo "BLOCKER=CORRECTED_METADATA_PILOT_CANARY_PLAN_NOT_READY"
    echo "NEXT_RECOMMENDED_BATCH=BATCH_098R4R2R1_PREFLIGHT_FAILURE_ANALYSIS"
fi

echo "REPORT_DIR=$OUT"
echo "============================================================"
