#!/usr/bin/env bash
set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 089"
echo " FINAL PYTHON REQUIREMENT CLASSIFICATION — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
ROOT="/mnt/c/FREYA_ASUS_NODE_888"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_089_$START_UTC"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=089"
echo "MODE=READ_ONLY_FINAL_PYTHON_REQUIREMENT_CLASSIFICATION"
echo "ROOT=$ROOT"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"

: > "$OUT/ALL_NONHISTORICAL_PYTHON.txt"
: > "$OUT/CANONICAL_PYTHON.txt"
: > "$OUT/AGENT_PYTHON.txt"
: > "$OUT/RUNTIME_PYTHON.txt"
: > "$OUT/CONTROL_EVIDENCE_PYTHON.txt"
: > "$OUT/FINAL_PYTHON_REQUIREMENT_STATUS.txt"

find "$ROOT" -type f -iname '*.py' 2>/dev/null \
| grep -Ev '/(08_ARCHIVES|11_BACKUP|90_QUARANTINE|99_ARCHIVE)/' \
| sort \
> "$OUT/ALL_NONHISTORICAL_PYTHON.txt"

grep -E \
'/((20|21|22|23|24|25)_CANONICAL[^/]*)/' \
"$OUT/ALL_NONHISTORICAL_PYTHON.txt" \
> "$OUT/CANONICAL_PYTHON.txt" || true

grep -E \
'/03_AGENTS_ACTIVE/' \
"$OUT/ALL_NONHISTORICAL_PYTHON.txt" \
> "$OUT/AGENT_PYTHON.txt" || true

grep -Ei \
'/(05_RUNTIME_UNION|AUTORUN_RUNTIME|RUNTIME)/' \
"$OUT/ALL_NONHISTORICAL_PYTHON.txt" \
> "$OUT/RUNTIME_PYTHON.txt" || true

grep -E \
'/00_CONTROL/' \
"$OUT/ALL_NONHISTORICAL_PYTHON.txt" \
> "$OUT/CONTROL_EVIDENCE_PYTHON.txt" || true

ALL_COUNT="$(wc -l < "$OUT/ALL_NONHISTORICAL_PYTHON.txt" | tr -d ' ')"
CANONICAL_COUNT="$(wc -l < "$OUT/CANONICAL_PYTHON.txt" | tr -d ' ')"
AGENT_COUNT="$(wc -l < "$OUT/AGENT_PYTHON.txt" | tr -d ' ')"
RUNTIME_COUNT="$(wc -l < "$OUT/RUNTIME_PYTHON.txt" | tr -d ' ')"
CONTROL_COUNT="$(wc -l < "$OUT/CONTROL_EVIDENCE_PYTHON.txt" | tr -d ' ')"

PYTHON3_STATUS="MISSING"
command -v python3 >/dev/null 2>&1 && PYTHON3_STATUS="AVAILABLE"

if (( CANONICAL_COUNT > 0 || AGENT_COUNT > 0 || RUNTIME_COUNT > 0 )); then
  PYTHON_REQUIREMENT="CONFIRMED_FOR_ACTIVE_ASUS_PATH"
else
  PYTHON_REQUIREMENT="NOT_PROVEN_FOR_ACTIVE_ASUS_PATH"
fi

if [[ "$PYTHON_REQUIREMENT" == "CONFIRMED_FOR_ACTIVE_ASUS_PATH" && \
      "$PYTHON3_STATUS" == "MISSING" ]]; then
  PYTHON_GAP_SEVERITY="HIGH"
else
  PYTHON_GAP_SEVERITY="NONE_PROVEN"
fi

cat > "$OUT/FINAL_PYTHON_REQUIREMENT_STATUS.txt" <<STATUS
PROTOCOL=888
NODE=FREYA_ASUS_DEBIAN_888

PYTHON_REQUIREMENT_CLASSIFICATION=COMPLETE

NONHISTORICAL_PYTHON_COUNT=$ALL_COUNT
CANONICAL_PYTHON_COUNT=$CANONICAL_COUNT
AGENT_PYTHON_COUNT=$AGENT_COUNT
RUNTIME_PYTHON_COUNT=$RUNTIME_COUNT
CONTROL_EVIDENCE_PYTHON_COUNT=$CONTROL_COUNT

PYTHON3_STATUS=$PYTHON3_STATUS
PYTHON_REQUIREMENT=$PYTHON_REQUIREMENT
PYTHON_GAP_SEVERITY=$PYTHON_GAP_SEVERITY

ACTIVE_AGENT_STATUS=NOT_OBSERVED

AUTOMATIC_INSTALL=DISABLED
AUTOMATIC_EXECUTION=DISABLED
AUTOMATIC_REPAIR=DISABLED

INSTALL_ALLOWED=NO
UPGRADE_ALLOWED=NO
EXECUTION_ALLOWED=NO
MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
MOVE_ALLOWED=NO
OVERWRITE_ALLOWED=NO
REPAIR_ALLOWED=NO
NETWORK_WRITE_ALLOWED=NO

MODE=HUMAN_GATE_CONTROLLED
STATUS

echo "--- SUMMARY ---"
cat "$OUT/FINAL_PYTHON_REQUIREMENT_STATUS.txt"

echo
echo "--- CANONICAL PYTHON SAMPLE ---"
head -30 "$OUT/CANONICAL_PYTHON.txt" || true

echo
echo "--- ACTIVE AGENT PYTHON SAMPLE ---"
head -30 "$OUT/AGENT_PYTHON.txt" || true

echo
echo "--- RUNTIME PYTHON SAMPLE ---"
head -30 "$OUT/RUNTIME_PYTHON.txt" || true

echo "============================================================"

if [[ "$PYTHON_GAP_SEVERITY" == "HIGH" ]]; then
  echo "RESULT=HOLD"
  echo "BLOCKER=PYTHON3_REQUIRED_BY_ACTIVE_ASUS_PATH"
  echo "REPORT_DIR=$OUT"
  echo "NEXT_RECOMMENDED_BATCH=BATCH_089R1_HUMAN_GATE_PYTHON_REMEDIATION_DECISION"
else
  echo "RESULT=PASS"
  echo "REPORT_DIR=$OUT"
  echo "NEXT_RECOMMENDED_BATCH=BATCH_090_FINAL_EXECUTION_CHAIN_STATUS"
fi

echo "============================================================"
