#!/usr/bin/env bash
set -euo pipefail

BASE="$HOME/FREYA_BUILDER"
READY="$BASE/10_DAEMON_READY_LAYER"
MAC="$BASE/09_MAC_PACKET_INTAKE"
VDR="$BASE/06_DATA_ROOM_BUILDER/150_VDR_SLOTS"

echo "FREYA ORCHESTRATOR — DRY RUN ONLY"
echo "NO_RUNTIME=YES"
echo "NO_DAEMON_EXECUTION=YES"
echo "HUMAN_GATE=ACTIVE"
echo ""

echo "PACKET_REGISTER:"
ls -lh "$MAC/01_PACKET_CANDIDATES/MAC_PACKET_CANDIDATES_HASHED.tsv"

echo ""
echo "VDR_SLOT_COUNT:"
find "$VDR" -maxdepth 1 -type d -name 'VDR_*' | wc -l

echo ""
echo "DAEMON REGISTRY:"
cat "$READY/01_DAEMON_REGISTRY/FREYA_DAEMON_REGISTRY.tsv"

echo ""
echo "ORCHESTRATOR CHAIN:"
cat "$READY/00_ORCHESTRATOR/FREYA_ORCHESTRATOR_CHAIN.tsv"

echo ""
echo "DRY_RUN_STATUS=COMPLETE"
