#!/usr/bin/env bash
set -Eeuo pipefail

echo "============================================================"
echo " MAGNUS — PROTOCOL 888 — ASUS DEBIAN BATCH 093R2R3"
echo " TASK REGISTRY EVIDENCE CHAIN ANALYSIS — READ ONLY"
echo "============================================================"

START_UTC="$(date -u +%Y%m%dT%H%M%SZ)"
ROOT="/mnt/c/FREYA_ASUS_NODE_888"
REPORT_ROOT="$HOME/FREYA_ASUS_DEBIAN_888/16_REPORTS"
OUT="$REPORT_ROOT/BATCH_093R2R3_$START_UTC"

TARGET_HASH="c719113415d0937e8298ae9dc82040065320d751862f4ccc281c36c1127495f8"

mkdir -p "$OUT"

{
echo "PROTOCOL=888"
echo "MACHINE=ASUS"
echo "NODE=FREYA_ASUS_DEBIAN_888"
echo "BATCH=093R2R3"
echo "MODE=READ_ONLY_TASK_REGISTRY_EVIDENCE_CHAIN_ANALYSIS"
echo "TARGET_HASH=$TARGET_HASH"
echo "START_UTC=$START_UTC"
} > "$OUT/BATCH.env"

: > "$OUT/HASH_EVIDENCE_LINES.txt"
: > "$OUT/REGISTRY_EVIDENCE.txt"
: > "$OUT/STATIC_CLASS_PROOF.txt"
: > "$OUT/FINAL_STATUS.txt"

echo "===== HASH EVIDENCE ====="

for f in \
  "$ROOT/02_REGISTRY/SHA256_REGISTRY.csv" \
  "$ROOT/02_REGISTRY/CANDIDATE_REGISTRY.csv" \
  "$ROOT/09_EVIDENCE/ASUS_PRO_BATCH_01_20260821T184317Z/HASH_INDEX.csv" \
  "$ROOT/09_EVIDENCE/ASUS_PRO_BATCH_01_20260821T184317Z/MUTATION_LEDGER.csv"
do
    [[ -f "$f" ]] || continue

    grep -inF "$TARGET_HASH" "$f" 2>/dev/null \
      | sed "s|^|FILE=$f :: |" \
      | tee -a "$OUT/HASH_EVIDENCE_LINES.txt" || true
done

HASH_EVIDENCE_COUNT="$(
  wc -l < "$OUT/HASH_EVIDENCE_LINES.txt" | tr -d ' '
)"

TASK_REGISTRY_NAME_SIGNAL_COUNT="$(
  grep -ic 'task_registry' "$OUT/HASH_EVIDENCE_LINES.txt" || true
)"

CANONICAL_SIGNAL_COUNT="$(
  grep -Eic 'canonical|validated|approved|active|agent|module' \
    "$OUT/HASH_EVIDENCE_LINES.txt" || true
)"

QUARANTINE_SIGNAL_COUNT="$(
  grep -Eic 'quarantine' "$OUT/HASH_EVIDENCE_LINES.txt" || true
)"

printf '%s\n' \
  "HASH_EVIDENCE_COUNT=$HASH_EVIDENCE_COUNT" \
  "TASK_REGISTRY_NAME_SIGNAL_COUNT=$TASK_REGISTRY_NAME_SIGNAL_COUNT" \
  "CANONICAL_SIGNAL_COUNT=$CANONICAL_SIGNAL_COUNT" \
  "QUARANTINE_SIGNAL_COUNT=$QUARANTINE_SIGNAL_COUNT" \
  > "$OUT/REGISTRY_EVIDENCE.txt"

echo
echo "===== STATIC CLASS PROOF ====="

TASKREGISTRY_COUNT=0
TASKSPEC_COUNT=0
PARSE_PASS_COUNT=0
PHYSICAL_COUNT=0

while IFS= read -r f; do
    [[ -f "$f" ]] || continue

    PHYSICAL_COUNT=$((PHYSICAL_COUNT + 1))

    RESULT="$(
      PYTHONDONTWRITEBYTECODE=1 python3 - "$f" <<'PY'
import ast
import sys
from pathlib import Path

p = Path(sys.argv[1])

try:
    tree = ast.parse(p.read_text(errors="replace"), filename=str(p))
except Exception as exc:
    print("PARSE=FAIL")
    print("TASKREGISTRY=0")
    print("TASKSPEC=0")
    raise SystemExit

classes = {
    n.name for n in ast.walk(tree)
    if isinstance(n, ast.ClassDef)
}

print("PARSE=PASS")
print("TASKREGISTRY=" + ("1" if "TaskRegistry" in classes else "0"))
print("TASKSPEC=" + ("1" if "TaskSpec" in classes else "0"))
PY
    )"

    echo "FILE=$f" >> "$OUT/STATIC_CLASS_PROOF.txt"
    echo "$RESULT" >> "$OUT/STATIC_CLASS_PROOF.txt"
    echo >> "$OUT/STATIC_CLASS_PROOF.txt"

    grep -q '^PARSE=PASS$' <<<"$RESULT" \
      && PARSE_PASS_COUNT=$((PARSE_PASS_COUNT + 1))

    grep -q '^TASKREGISTRY=1$' <<<"$RESULT" \
      && TASKREGISTRY_COUNT=$((TASKREGISTRY_COUNT + 1))

    grep -q '^TASKSPEC=1$' <<<"$RESULT" \
      && TASKSPEC_COUNT=$((TASKSPEC_COUNT + 1))

done < <(
  find "$ROOT/90_QUARANTINE" \
    -type f \
    -name 'task_registry.py' \
    2>/dev/null |
  sort
)

cat "$OUT/STATIC_CLASS_PROOF.txt"

if (( PHYSICAL_COUNT > 0 &&
      PARSE_PASS_COUNT == PHYSICAL_COUNT &&
      TASKREGISTRY_COUNT == PHYSICAL_COUNT &&
      TASKSPEC_COUNT == PHYSICAL_COUNT )); then
    STATIC_IMPLEMENTATION_PROOF="PROVEN"
else
    STATIC_IMPLEMENTATION_PROOF="NOT_PROVEN"
fi

if (( HASH_EVIDENCE_COUNT > 0 &&
      TASK_REGISTRY_NAME_SIGNAL_COUNT > 0 )); then
    REGISTRY_PROVENANCE_PROOF="PROVEN"
else
    REGISTRY_PROVENANCE_PROOF="NOT_PROVEN"
fi

if [[ "$STATIC_IMPLEMENTATION_PROOF" == "PROVEN" &&
      "$REGISTRY_PROVENANCE_PROOF" == "PROVEN" ]]; then
    FINAL_PROVENANCE_STATUS="PROVEN"
else
    FINAL_PROVENANCE_STATUS="NOT_PROVEN"
fi

cat > "$OUT/FINAL_STATUS.txt" <<STATUS
PROTOCOL=888
NODE=FREYA_ASUS_DEBIAN_888

TASK_REGISTRY_EVIDENCE_CHAIN_AUDIT=COMPLETE

TARGET_HASH=$TARGET_HASH

PHYSICAL_TASK_REGISTRY_COUNT=$PHYSICAL_COUNT
PARSE_PASS_COUNT=$PARSE_PASS_COUNT
TASKREGISTRY_CLASS_COUNT=$TASKREGISTRY_COUNT
TASKSPEC_CLASS_COUNT=$TASKSPEC_COUNT

HASH_EVIDENCE_COUNT=$HASH_EVIDENCE_COUNT
TASK_REGISTRY_NAME_SIGNAL_COUNT=$TASK_REGISTRY_NAME_SIGNAL_COUNT
CANONICAL_SIGNAL_COUNT=$CANONICAL_SIGNAL_COUNT
QUARANTINE_SIGNAL_COUNT=$QUARANTINE_SIGNAL_COUNT

STATIC_IMPLEMENTATION_PROOF=$STATIC_IMPLEMENTATION_PROOF
REGISTRY_PROVENANCE_PROOF=$REGISTRY_PROVENANCE_PROOF
FINAL_PROVENANCE_STATUS=$FINAL_PROVENANCE_STATUS

QUARANTINE_IMPORT_ALLOWED=NO
QUARANTINE_EXECUTION_ALLOWED=NO

FILE_COPY_EXECUTED=NO
FILE_MOVE_EXECUTED=NO
FILE_EXTRACTION_EXECUTED=NO
PYTHONPATH_CHANGE_EXECUTED=NO
AGENT_EXECUTION_EXECUTED=NO

MUTATION_ALLOWED=NO
DELETE_ALLOWED=NO
REPAIR_ALLOWED=NO

MODE=HUMAN_GATE_CONTROLLED
STATUS

echo
echo "--- FINAL STATUS ---"
cat "$OUT/FINAL_STATUS.txt"

echo
echo "--- REGISTRY EVIDENCE ---"
cat "$OUT/HASH_EVIDENCE_LINES.txt"

echo "============================================================"

if [[ "$FINAL_PROVENANCE_STATUS" == "PROVEN" ]]; then
    echo "RESULT=PASS"
    echo "NEXT_RECOMMENDED_BATCH=BATCH_093R3_TASK_REGISTRY_RECONSTRUCTION_PLAN"
else
    echo "RESULT=HOLD"
    echo "BLOCKER=TASK_REGISTRY_EVIDENCE_CHAIN_INCOMPLETE"
    echo "NEXT_RECOMMENDED_BATCH=BATCH_093R2R4_REGISTRY_RECORD_DEEP_ANALYSIS"
fi

echo "REPORT_DIR=$OUT"
echo "============================================================"
