#!/bin/sh
set -eu
BRIDGE="/root/FREYA_IPHONE_ISH_NODE_888/SHORTCUTS_BRIDGE_888"
INBOX="$BRIDGE/01_INBOX"
MAN="$BRIDGE/05_MANIFESTS"
mkdir -p "$INBOX" "$MAN"
echo "PROTOCOL=888"
echo "ENGINE=FREYA_888_LIVE_INTAKE"
echo "INBOX=$INBOX"
echo "FILE_COUNT=$(find "$INBOX" -type f | wc -l)"
echo "INTAKE_STATUS=LIVE"
echo "ORIGINALS_PRESERVED=YES"
echo "RESULT=PASS"
