# This file is part of cloud-init. See LICENSE file for license information.
# Automatically generated by Meson. Do not edit this file directly

UPSTREAM_VERSION = "26.1"      # Required to release
DOWNSTREAM_VERSION = "26.1-0ubuntu2"  # Optional for downstream packagers
