#!/bin/sh
R="$HOME/FREYA_IPHONE_ISH_NODE_888/16_V2_DEVELOPMENT/PRODUCTION/FREYA_V2_PRODUCTION_CURRENT/agent_intelligence_888"

PASS=1

for f in \
PROFESSION_EXPERTISE.tsv \
MASTER_DOCTRINE_888.env \
VALIDATOR_REGISTRY.env \
INPUT_OUTPUT_CONTRACT.env \
FINANCIAL_MODEL_REGISTRY.tsv \
AGENT_FINANCIAL_BINDING.tsv \
AGENT_CHAIN_REGISTRY.tsv \
FINAL_AGENT_CENSUS.env \
financial_validator_888.py
do
  [ -s "$R/$f" ] || PASS=0
done

[ "$PASS" -eq 1 ] && echo "INTELLIGENCE_HEALTH=PASS" || echo "INTELLIGENCE_HEALTH=HOLD"
echo "NETWORK_WRITE=0"
echo "AUTO_EXTERNAL_SEND=DENY"
exit $((1-PASS))
