#!/bin/sh
set -eu
BRIDGE="/root/FREYA_IPHONE_ISH_NODE_888/SHORTCUTS_BRIDGE_888"
echo "PROTOCOL=888"
echo "ENGINE=FREYA_SHORTCUTS_BRIDGE_888"
echo "ENGINE_STATUS=LIVE"
echo "INBOX=$BRIDGE/01_INBOX"
echo "OUTBOX=$BRIDGE/02_OUTBOX"
echo "ASUS_HANDOFF=$BRIDGE/06_ASUS_HANDOFF"
echo "HUMAN_GATE=ACTIVE"
