#!/bin/sh
set -eu
BRIDGE="/root/FREYA_IPHONE_ISH_NODE_888/SHORTCUTS_BRIDGE_888"
INBOX="$BRIDGE/01_INBOX"
PKGROOT="$BRIDGE/08_PACKAGES"
MAN="$BRIDGE/05_MANIFESTS/LATEST_SHA256_MANIFEST.txt"
COUNT=$(find "$INBOX" -type f | wc -l | tr -d " ")
echo "PROTOCOL=888"
echo "ENGINE=FREYA_PACKAGE_BUILDER"
echo "SOURCE_FILE_COUNT=$COUNT"
if [ "$COUNT" -eq 0 ]; then
 echo "PACKAGE_CREATED=NO"
 echo "HOLD_REASON=INTAKE_EMPTY"
 echo "RESULT=READY_WAITING_FOR_DOCUMENT"
 exit 0
fi
TS=$(date -u +%Y%m%dT%H%M%SZ)
PKG="$PKGROOT/FREYA_IPHONE_TO_ASUS_$TS.tar.gz"
mkdir -p "$PKGROOT"
tar -czf "$PKG" -C "$BRIDGE" 01_INBOX 05_MANIFESTS/LATEST_SHA256_MANIFEST.txt
echo "PACKAGE=$PKG"
echo "PACKAGE_SHA256=$(sha256sum "$PKG" | awk "{print \$1}")"
echo "PACKAGE_CREATED=YES"
echo "TARGET=ASUS_DANIJELA"
echo "TRANSFER_EXECUTED=NO"
echo "RESULT=PASS"
