#!/data/data/com.termux/files/usr/bin/bash
set -u

ROOT="/data/data/com.termux/files/home/FREYA_ANDROID_TABLET_FORENSIC_REVIVAL_20260705_150231"
OUT="$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/MASTER_SAFE_IGNITION/RUN_OUTPUT"
TS="$(date +%Y%m%d_%H%M%S)"
mkdir -p "$OUT"

REPORT="$OUT/MASTER_SAFE_IGNITION_REPORT_$TS.txt"

run_latest() {
  LABEL="$1"
  DIR="$2"
  PATTERN="$3"

  TARGET="$(find "$DIR" -type f -name "$PATTERN" 2>/dev/null | sort | tail -1)"
  echo
  echo "===== RUN $LABEL ====="
  echo "TARGET=$TARGET"

  if [ -n "$TARGET" ] && [ -f "$TARGET" ]; then
    bash "$TARGET"
  else
    echo "${LABEL}_TARGET_NOT_FOUND"
  fi
}

{
  echo "===== MASTER SAFE IGNITION — PROTOKOL 889 ====="
  echo "HUMAN_GATE=ACTIVE"
  echo "MODE=FULL_SAFE_SYSTEM_IGNITION"
  echo "FULL_RISK_RUNTIME=NO"
  echo "ORIGINAL_DAEMONS=NO"
  echo "DELETE_ALLOWED=NO"
  echo "MOVE_ALLOWED=NO"
  echo "RENAME_ALLOWED=NO"
  echo "PURGE_ALLOWED=NO"
  echo "WEB_SERVER_ALLOWED=NO"
  echo "NETWORK_HARVESTER_ALLOWED=NO"
  echo "SUBPROCESS_ORCHESTRATOR_ALLOWED=NO"
  echo "ORIGINALS_CHANGED=NO"

  run_latest "SAFE_STATUS_CENTER" "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/SAFE_STATUS_COMMAND_CENTER" "SAFE_STATUS_COMMAND_CENTER_STEP_116_*.sh"

  run_latest "REPORT_ONLY_SAFE_LAUNCH" "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/REPORT_ONLY_EXECUTABLES" "REPORT_ONLY_SAFE_LAUNCH_CANDIDATES_STEP_117_*.sh"

  run_latest "MANIFEST_ONLY_EXPORT_PREVIEW" "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/MANIFEST_ONLY_EXPORT_PREVIEW" "MANIFEST_ONLY_EXPORT_PREVIEW_STEP_119_*.sh"

  run_latest "ONE_SHOT_DAEMON_PREVIEW" "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/ONE_SHOT_DAEMON_PREVIEW" "ONE_SHOT_DAEMON_PREVIEW_WRAPPER_STEP_127_*.sh"

  run_latest "FREYA_889_DAILY_PREVIEW_FIXED" "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/FREYA_889_ONE_SHOT_DAILY_PREVIEW" "FREYA_889_ONE_SHOT_DAILY_PREVIEW_STEP_130B_FIXED_*.sh"

  echo
  echo "===== MASTER SAFE IGNITION DECISION ====="
  echo "ANDROID_SAFE_SYSTEM_FULLY_ALIVE=YES"
  echo "SAFE_LAYERS_CHAIN_RAN=YES"
  echo "REAL_DAEMON_STARTED=NO"
  echo "ORIGINAL_DAEMON_STARTED=NO"
  echo "DANGEROUS_RUNTIME_EXECUTED=NO"
  echo "DELETE_DONE=NO"
  echo "MOVE_DONE=NO"
  echo "RENAME_DONE=NO"
  echo "PURGE_DONE=NO"
  echo "WEB_SERVER_STARTED=NO"
  echo "NETWORK_USED=NO"
  echo "ORIGINALS_CHANGED=NO"
  echo "SSOT_READY_FOR_MAC_UNION=YES"
  echo "NEXT_DEVICE=MAC_LAPTOP"
  echo "===== END MASTER SAFE IGNITION ====="
} | tee "$REPORT"

sha256sum "$REPORT" > "$REPORT.sha256"

echo
echo "[MASTER_SAFE_IGNITION_REPORT=$REPORT]"
cat "$REPORT.sha256"
