#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
umask 077

SOURCE_ROOT="${1:-}"
BLACK_SSOT_ROOT="${2:-}"

echo "============================================================"
echo "FREYA BLACK SSOT SAFE WORKER"
echo "============================================================"
echo "WORKER_ID=BLACK_SSOT_WORKER_000065"
echo "CANON_SCRIPT_ID=CANON_SCRIPT_000065"
echo "SOURCE_SHA256=1a16639a0505ff76a9196480cc8da81daf7fe38f23734ac08912dd81a66db9b8"
echo "ASSIGNED_ROLE=MANIFEST_LINEAGE_WORKER"
echo "ORIGINAL_RECORDS_REPRESENTED=10"
echo "UNSAFE_DIRECTIVES_LINKED=0"
echo "HUMAN_GATE=ACTIVE"
echo "PROTOKOL=888"
echo "DELETE=NO"
echo "MOVE_SOURCE=NO"
echo "RENAME_SOURCE=NO"
echo "OVERWRITE=NO"
echo "AUTO_INTERNET=NO"
echo "PERSISTENT_DAEMON=NO"
echo "SOURCE_EXECUTION=NO"
echo

if [ -z "$SOURCE_ROOT" ] || [ -z "$BLACK_SSOT_ROOT" ]; then
    echo "USAGE=$0 SOURCE_ROOT BLACK_SSOT_ROOT"
    echo "FINAL_STATUS=BLOCKED_ARGUMENTS_REQUIRED"
    exit 2
fi

if [ ! -d "$SOURCE_ROOT" ]; then
    echo "FINAL_STATUS=BLOCKED_SOURCE_ROOT_NOT_FOUND"
    exit 3
fi

if [ ! -d "$BLACK_SSOT_ROOT" ]; then
    echo "FINAL_STATUS=BLOCKED_BLACK_SSOT_ROOT_NOT_FOUND"
    exit 4
fi

echo "SOURCE_ROOT=$SOURCE_ROOT"
echo "BLACK_SSOT_ROOT=$BLACK_SSOT_ROOT"

echo "PLANNED_FUNCTION=CREATE_MANIFEST_AND_SOURCE_LINEAGE_REGISTER"
echo "MANIFEST_CREATED=NO"
echo "NEXT_STATUS=READY_FOR_STATIC_MANIFEST_BUILD"

echo "FILES_CHANGED=NO"
echo "FILES_DELETED=NO"
echo "FILES_MOVED=NO"
echo "FILES_RENAMED=NO"
echo "FINAL_STATUS=SAFE_BLACK_SSOT_WORKER_VALIDATED_NOT_EXECUTED"
