#!/data/data/com.termux/files/usr/bin/bash
set -u

ROOT="/data/data/com.termux/files/home/FREYA_ANDROID_TABLET_FORENSIC_REVIVAL_20260705_150231"
OUT="$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/REPORT_ONLY_EXECUTABLES/RUN_OUTPUT"
TS="$(date +%Y%m%d_%H%M%S)"
mkdir -p "$OUT"

REPORT="$OUT/SAFE_LAUNCH_CANDIDATES_RUNTIME_REPORT_$TS.txt"

{
  echo "===== REPORT ONLY SAFE LAUNCH CANDIDATES — PROTOKOL 889 ====="
  echo "HUMAN_GATE=ACTIVE"
  echo "MODE=REPORT_ONLY_EXECUTABLE"
  echo "DELETE_ALLOWED=NO"
  echo "MOVE_ALLOWED=NO"
  echo "RENAME_ALLOWED=NO"
  echo "DAEMON_ALLOWED=NO"
  echo "RUNTIME_ALLOWED=REPORT_ONLY_SAFE"
  echo "ORIGINALS_CHANGED=NO"
  echo

  echo "[INPUTS]"
  echo "LOCK_CARD=$(find "$ROOT/20_RUNTIME_STATIC_REVIEW_LOCK" -type f -name "RUNTIME_STATIC_REVIEW_LOCK_STEP_102_*.txt" 2>/dev/null | sort | tail -1)"
  echo "PATCH_INDEX=$(find "$ROOT/21_DRY_RUN_PATCH_DESIGNS" -type f -name "PATCH_DRAFTS_MASTER_INDEX_STEP_111_*.tsv" 2>/dev/null | sort | tail -1)"
  echo "SAFE_CANDIDATES=$(find "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/SAFE_LAUNCH_CANDIDATES" -type f -name "SAFE_LAUNCH_CANDIDATES_REPORT_STEP_115_*.tsv" 2>/dev/null | sort | tail -1)"
  echo

  echo "[COUNTS]"
  echo "PATCH_DRAFT_COUNT=$(find "$ROOT/21_DRY_RUN_PATCH_DESIGNS/PATCH_DRAFTS" -type f -name "PATCH_DRAFT_*" ! -name "*.sha256" 2>/dev/null | wc -l)"
  echo "SAFE_CANDIDATE_REPORT_COUNT=$(find "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/SAFE_LAUNCH_CANDIDATES" -type f -name "SAFE_LAUNCH_CANDIDATES_REPORT_STEP_115_*.tsv" 2>/dev/null | wc -l)"
  echo

  echo "[RELEASE DECISION]"
  echo "SAFE_PREVIEW_LAYER=LIVE"
  echo "REPORT_ONLY_LAYER=LIVE"
  echo "REAL_RUNTIME_LAYER=BLOCKED"
  echo "DAEMON_LAYER=BLOCKED"
  echo "DELETE_MOVE_PURGE_LAYER=BLOCKED"
  echo "SYSTEM_RELEASE=NOT_YET"
  echo

  echo "[NEXT]"
  echo "NEXT_SAFE_STEP=CREATE_MANIFEST_ONLY_EXPORT_PREVIEW"
  echo

  echo "SCRIPT_EXECUTED=YES_REPORT_ONLY"
  echo "DANGEROUS_RUNTIME_EXECUTED=NO"
  echo "DAEMON_STARTED=NO"
  echo "DELETE_DONE=NO"
  echo "MOVE_DONE=NO"
  echo "RENAME_DONE=NO"
  echo "ORIGINALS_CHANGED=NO"
  echo "===== END REPORT ONLY SAFE LAUNCH CANDIDATES ====="
} | tee "$REPORT"

sha256sum "$REPORT" > "$REPORT.sha256"

echo
echo "[REPORT_OUTPUT=$REPORT]"
cat "$REPORT.sha256"
