#!/data/data/com.termux/files/usr/bin/bash
set -u

ROOT="/data/data/com.termux/files/home/FREYA_ANDROID_TABLET_FORENSIC_REVIVAL_20260705_150231"

echo "===== SAFE ANDROID MENU V1 — PROTOKOL 889 ====="
echo "HUMAN_GATE=ACTIVE"
echo "MODE=SAFE_MENU_ONLY"
echo "DELETE_ALLOWED=NO"
echo "MOVE_ALLOWED=NO"
echo "RENAME_ALLOWED=NO"
echo "DAEMON_ALLOWED=NO"
echo "WEB_SERVER_ALLOWED=NO"
echo "SUBPROCESS_ALLOWED=NO"
echo "ORIGINALS_CHANGED=NO"
echo

echo "[MENU]"
echo "1_STATUS_CENTER=SAFE"
echo "2_REPORT_ONLY_SAFE_LAUNCH=SAFE"
echo "3_MANIFEST_ONLY_EXPORT_PREVIEW=SAFE"
echo "4_RELEASE_GATE_CARD=SAFE_READ"
echo "5_BLOCKED_RUNTIME_FAMILIES=SAFE_READ"
echo

echo "[AUTO RUN SAFE STATUS CENTER]"
CENTER="$(find "$ROOT/22_ANDROID_SAFE_REVIVAL_PLAN/SAFE_STATUS_COMMAND_CENTER" -type f -name "SAFE_STATUS_COMMAND_CENTER_STEP_116_*.sh" 2>/dev/null | sort | tail -1)"
if [ -n "$CENTER" ]; then
  bash "$CENTER"
else
  echo "CENTER_NOT_FOUND"
fi

echo
echo "[SAFE MENU DECISION]"
echo "MENU_RAN=YES"
echo "ONLY_SAFE_STATUS_CENTER_CALLED=YES"
echo "REPORT_ONLY_NOT_AUTO_RUN=YES"
echo "MANIFEST_ONLY_NOT_AUTO_RUN=YES"
echo "DANGEROUS_RUNTIME_EXECUTED=NO"
echo "DAEMON_STARTED=NO"
echo "DELETE_DONE=NO"
echo "MOVE_DONE=NO"
echo "RENAME_DONE=NO"
echo "ORIGINALS_CHANGED=NO"
echo "NEXT_SAFE_STEP=OPTIONAL_RUN_REPORT_OR_MANIFEST_FROM_MENU"
echo "===== END SAFE ANDROID MENU V1 ====="
