#!/bin/sh
set -eu

PROTOCOL=888
NODE=FREYA_IPHONE_NODE_888
DEFAULT_MODE=DENY
READ_ONLY_FIRST=YES
EVIDENCE_FIRST=YES

MODE="${1:-audit}"
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
SOURCE_ALLOWLIST="$SCRIPT_DIR/SOURCE_ALLOWLIST.txt"
TARGET_ROOT="/root/CENTRALNI_MODUL_UCENJA/DOKTRINE_I_SIGNALI"
STAGING_ROOT="$SCRIPT_DIR/STAGING"

case "$MODE" in
    audit|plan)
        ;;
    *)
        echo "RESULT=DENY"
        echo "BLOCKED_REASON=UNAPPROVED_MODE"
        echo "ALLOWED_MODES=audit,plan"
        exit 64
        ;;
esac

echo "PROTOCOL=$PROTOCOL"
echo "NODE=$NODE"
echo "RESULT=PASS"
echo "MODE=$MODE"
echo "DEFAULT_MODE=$DEFAULT_MODE"
echo "READ_ONLY_FIRST=$READ_ONLY_FIRST"
echo "EVIDENCE_FIRST=$EVIDENCE_FIRST"
echo "SOURCE_ALLOWLIST=$SOURCE_ALLOWLIST"
echo "TARGET_ROOT=$TARGET_ROOT"
echo "STAGING_ROOT=$STAGING_ROOT"
echo "SCAN_ETC=NO"
echo "OVERWRITE_ALLOWED=NO"
echo "DELETE_ALLOWED=NO"
echo "MOVE_ALLOWED=NO"
echo "NETWORK_ALLOWED=NO"
echo "HARVEST_EXECUTED=NO"
echo "FILES_COPIED=0"
echo "SOURCE_FILES_MODIFIED=NO"
echo "TARGET_FILES_MODIFIED=NO"
echo "NEXT_REQUIRED_STEP=CREATE_SAFE_CANONICAL_SCRIPT_PART_2_ALLOWLIST_VALIDATOR"
